<?php $this->headTitle('Configurações'); ?>

<div class="grid_16">
	<div class="page-header">
		<h1>Configurações
			<small>Insira alguns dados para configurações globais</small></h1>
	</div>
	
	<br /> 
	
	<div class="container">
		<form action="/admin/configs/insert" method="post"  class="form-horizontal">
				<div class="control-group">
					<label class="control-label">Valor do Crédito:</label>
					<div class="controls">
						<input type="text" name="configs[valor_credito]" value="<?php echo $this->valor_credito; ?>"/>
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" >Fechamento da Fatura:</label>
					<div class="controls">
						<input type="text" name="configs[dia_fatura]" value="<?php echo $this->dia_fatura; ?>" />
						<span class="help-block">Defina quantos dias antes do mês a fatura deve ser fechada.</span>
					</div>
				</div>

				<div class="control-group">
					<label class="control-label" >Ano Atual:</label>
					<div class="controls">
						<input type="text" name="configs[ano_atual]" value="<?php echo $this->ano_atual; ?>" />
					</div>
				</div>

				<div class="control-group">
					<label class="control-label" >Semestre Atual:</label>
					<div class="controls">
						<input type="text" name="configs[semestre_atual]" value="<?php echo $this->semestre_atual; ?>" />
					</div>
				</div>

				<div class="control-group">
					<div class="controls">
						<input class="btn btn-primary" type="submit" value="Salvar" name="configs_btn"/>
					</div>
				</div>

		</form>
	</div>
</div>

