<?php $this->headTitle('Listagem de Serviços'); ?>

<div class="grid_16">
	<div class="page-header">
		<h1>Serviços Cadastrados
			<small>Veja toda a lista dos serviços cadastrados</small>
		</h1>
	</div>
	<table class="table table-striped data-table">
		<thead>
			<tr>
				<th><font size="2" color="black"><strong>#</strong></font></th>
				<th><font size="2" color="black"><strong>Nome</strong></font></th>
				<th><font size="2" color="black"><strong>Descrição</strong></font></th>
				<th style="text-align: center;"><font size="2" color="black"><strong>Valor</strong></font></th>
				<th style="text-align: center;"><font size="2" color="black"><strong>Ações</strong></font></th>
			</tr>
		</thead>
		<tbody>
	<?php foreach ($this->rows as $lista){ ?>
		<tr style="background: #EEE; ">
			<td style="width: 30px;"><strong><?php echo $lista->idServicos; ?></strong></td>
			<td style="width: 250px;"><strong><?php echo $lista->nome; ?></strong></td>
			<td style="width: 300px;"><strong><?php echo $lista->descricao; ?></strong></td>
			<td style="width: 200px; text-align: center;"><strong><?php echo 'R$ ' . number_format($lista->valor,2,',','.'); ?></strong></td>
			<td style="text-align: center; width: 250px;">
				<a id="btn-admin" class="btn btn-primary" href="<?php echo $this->url(
					array(
						'controller' => 'servicos',
						'action'	 => 'editar',
						'idServicos' => $lista->idServicos
					));?>">
						Editar
				</a>
				
				<?php if($lista->status == 'ativo'){ ?>
				
				<a id="btn-admin" class="btn btn-danger" href="<?php echo $this->url(
					array(
						'controller' => 'servicos',
						'action'	 => 'desativa',
						'idServicos' => $lista->idServicos
					));?>">
						Desativar
				</a>
				
				<?php } else { ?>
				
				<a id="btn-admin" class="btn btn-success" href="<?php echo $this->url(
					array(
						'controller' => 'servicos',
						'action'	 => 'ativa',
						'idServicos' => $lista->idServicos
					));?>">
						Ativar Serviço
				</a>
				
				<?php } ?>
				
			</td>
		</tr>
	<?php }?>
	</tbody>
	
</table>

	<br /><br />
	
</div>