<?php $this->headTitle('Listagem de Serviços'); ?>

<div class="grid_16">
	<div class="page-header">
		<h1>Serviços Cadastrados
			<small>Veja toda a lista dos serviços cadastrados</small>
		</h1>
	</div>
	<table class="table table-striped data-table" style="margin-bottom:0;">
		<thead>
			<tr>
				<th>#</th>
				<th>Nome</th>
				<th>Descrição</th>
				<th>Valor</th>
				<th>Ações</th>
			</tr>
		</thead>
		<tbody>
	<?php foreach ($this->rows as $lista){ ?>
		<tr>
			<td><?php echo $lista->idServicos; ?></td>
			<td><?php echo $lista->nome; ?></td>
			<td><?php echo $lista->descricao; ?></td>
			<td><?php echo $lista->valor; ?></td>
			<td>
				<a class="btn btn-primary" href="<?php echo $this->url(
					array(
						'controller' => 'servicos',
						'action'	 => 'editar',
						'idServicos' => $lista->idServicos
					));?>">
						Editar
				</a>
				
				<a class="btn btn-warning" href="<?php echo $this->url(
					array(
						'controller' => 'servicos',
						'action'	 => 'delete',
						'idServicos' => $lista->idServicos
					));?>">
						Excluir
				</a>
			</td>
		</tr>
<?php }?>
	</tbody>
	</table>
</div>
