<?php $this->headTitle('Listagem de Serviços'); ?>

<div class="grid_16">
	<div class="page-header">
		<h1>Serviços Cadastrados
			<small>Veja toda a lista dos serviços cadastrados</small>
		</h1>
	</div>
	<table class="table table-striped data-table" style="margin-bottom:0;">
		<thead>
			<tr>
				<th><h5>#</h5></th>
				<th><h5>Nome</h5></th>
				<th><h5>Descrição</h5></th>
				<th><h5>Valor</h5></th>
				<th><h5>Ações</h5></th>
			</tr>
		</thead>
		<tbody>
	<?php foreach ($this->rows as $lista){ ?>
		<tr>
			<td><strong><?php echo $lista->idServicos; ?></strong></td>
			<td><strong><?php echo $lista->nome; ?></strong></td>
			<td><strong><?php echo $lista->descricao; ?></strong></td>
			<td><strong><?php echo $lista->valor; ?></strong></td>
			<td>
				<a class="btn btn-primary" href="<?php echo $this->url(
					array(
						'controller' => 'servicos',
						'action'	 => 'editar',
						'idServicos' => $lista->idServicos
					));?>">
						Editar
				</a>
				
				<a class="btn btn-warning" href="<?php echo $this->url(
					array(
						'controller' => 'servicos',
						'action'	 => 'delete',
						'idServicos' => $lista->idServicos
					));?>">
						Excluir
				</a>
			</td>
		</tr>
	<?php }?>
	</tbody>
</table>
	<br /><br />
</div>