<?php $this->headTitle('Início'); ?>

<h3>
	<img src="/../files/<?= $this->data->Foto; ?>" width="60" height="90"></img>
</h3>
					
	<h4><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'matricula','action'=>'index'),null,1); ?>">Matrícula</a></h4>
	<h4><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'usuario','action'=>'index'),null,1); ?>">Cadastrar Usuário</a></h4>
	<h4><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'curso','action'=>'index'),null,1); ?>">Cadastrar Curso</a></h4>
	<h4><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'disciplina','action'=>'index'),null,1); ?>">Cadastrar Disciplina</a></h4>
	<h4><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'turma','action'=>'index'),null,1); ?>">Cadastrar Turma</a></h4>
	<h4><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'igreja','action'=>'index'),null,1); ?>">Cadastrar Igreja</a></h4>
	<h4><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'servicos','action'=>'index'),null,1); ?>">Cadastrar Serviços</a></h4>
	<h4><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'debitos','action'=>'index'),null,1); ?>">Débitos</a></h4>
	<h4><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'faturas','action'=>'index'),null,1); ?>">Fatura</a></h4>
	<h4><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'pagamento','action'=>'index'),null,1); ?>">Pagamento</a></h4>
	<h4><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'minhasturmas','action'=>'index'),null,1); ?>">Minhas Turmas</a></h4>
	<h4><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'financeiro','action'=>'index'),null,1); ?>">Financeiro</a></h4>
	<h4><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'index','action'=>'altera-senha'),null,1); ?>">Alterar Senha</a></h4>
	