<?php $this->headTitle('Informações sobre o sistema'); ?>

<div class="grid_16">
	<br /><br /><br /><br />
	<div class="page-header">
		<h4>
			Sistema Acadêmico voltado para Seminários ou Instituições religiosas.
			O projeto foi criado e desenvolvido por <a target="_blank" href="https://www.facebook.com/eliakim.aquino2">Eliakim Aquino</a>
		</h4>
	<br /><br /><br /><br />
	</div>
</div>
<br /><br /><br /><br />