<?php $this->headTitle('Início'); ?>

<div class="grid_16">
	<div class="page-header">
		<h1>Dashboard
			<small>Seja bem vindo</small>
		</h1>
	</div>

	<div class="row">
		<div class="span12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Débitos não faturados</h3>
				</div>
				<div class="panel-body">
					<p>Os Débitos não faturados incidirão automaticamente na próxima fatura ou em fatura a ser definida pela Administração.</p>
					<table class="table table-bordered data-table">
						<thead>
						<tr>
							<td>#</td>
							<td>Descrição</td>
							<td>Mês/Ano</td>
							<td>Valor</td>
						</tr>
						</thead>
						<tbody>
							<?php
								$auth = Zend_Auth::getInstance();
								$data = $auth->getStorage()->read();
								$user_id = $data->idUsuario;

								$debitos_model = new Application_Model_DbTable_Debitos();
								$debitos = $debitos_model->listar(null,null,$user_id);
								$valor_total = 0;
								foreach($debitos as $debito) :
							?>
							<tr>
								<td><?php echo $debito['idDebitos']; ?> </td>
								<td><?php
									$desc_debito = '';
									if ( $debito['type'] == 'servico' ) {
										$desc_debito = "Serviço: " . $debito['servico']['nome_servico'];
									} else if ( $debito['type'] == 'matricula' ) {
										$desc_debito = 'Matrícula: ' . $debito['matricula']['nome_turma'] .
										               " ({$debito['matricula']['disciplina']}) {$debito['matricula']['ano_turma']}.{$debito['matricula']['semestre_turma']}";
									}
									echo $desc_debito;
									?></td>
								<td><?php echo $debito['mesPagamento'] .'/' . $debito['anoPagamento'];?></td>
								<td>
									<?php
										$valor = $debito[$debito['type']]['valor_final'];
										$valor_total += $valor;
										echo number_format($valor,2) . " (" . $debito['descontoMes'] . "%)";
									?>
								</td>
							</tr>
							<?php endforeach; ?>
						</tbody>
						<tfoot>
							<tr style="background: #EEE;">
								<td></td>
								<td></td>
								<td><font size="2" color="black"><strong>Total</strong></font></td>
								<td><font size="2" color="black"><strong>R$ <?php echo number_format($valor_total, 2); ?></strong></font></td>
							</tr>
						</tfoot>

					</table>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
		<div class="span12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Faturas</h3>
				</div>
				<div class="panel-body">
					<p>Aqui são listadas todas as faturas disponíveis</p>
					<table class="table table-bordered  data-table">
						<thead>
							<tr>
								<td>#</td>
								<td>Mês/Ano</td>
								<td>Valor Pendente</td>
								<td>Ações</td>
							</tr>
						</thead>

						<?php
							$faturas_model = new Application_Model_DbTable_Faturas();
							$faturas = $faturas_model->listar($user_id);

							foreach($faturas as $fatura) :
						?>
							<tr>
								<td>
									<div class="modal hide fade" id="fatura-pagamentos-<?php echo $fatura['idFatura']; ?>">
										<div class="modal-header">
											<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
											<h3>Listagem de pagamentos da Fatura #<?php echo $fatura['idFatura']; ?></h3>
										</div>
										<div class="modal-body">
											<table class="table table-striped">
												<tr>
													<th>#</th>
													<th>Valor</th>
													<th>Data</th>
												</tr>
												<tbody>
												<?php
												$valor_total_pagamentos = 0;
												$pagamentos_model = new Application_Model_DbTable_Pagamento();
												$pagamentos = $pagamentos_model->listar($fatura['idFatura']);
												foreach($pagamentos as $pagamento) : ?>
													<tr>
														<td><?php echo $pagamento->idPagamento; ; ?></td>
														<td>
															R$ <?php echo number_format($pagamento->valorPagamento,2); $valor_total_pagamentos += $pagamento->valorPagamento; ?>
														</td>
														<td><?php echo date('d/m/Y', strtotime($pagamento->dataPagamento)); ?></td>
													</tr>
												<?php endforeach; ?>
												<tr>
													<td><strong>Total:</strong></td>
													<td><strong>R$ <?php echo number_format($valor_total_pagamentos, 2); ?></strong></td>
													<td></td>
												</tr>
												</tbody>
											</table>
										</div>
										<div class="modal-footer">
											<a href="#" class="btn" data-dismiss="modal">Fechar</a>
										</div>
									</div>
									<?php echo $fatura['idFatura']; ?>
								</td>
								<td style="width: 30px; text-align: center; "><strong><?php echo $fatura['mes'] . '/' . $fatura['ano']; ?></strong></td>
								<td>
									<?php
										$valor = $fatura['valorFatura'] -  ($fatura['valorFatura'] *  $fatura['desconto']/100);
										$valor_pendente = number_format($valor - $valor_total_pagamentos,2);
										$pago = ( $valor_pendente <= 0) ? true : false;
									?>
									<?php if ( $pago ) : ?>
										<span class="label label-success">Pago</span>
									<?php else: ?>
										<?php echo $valor_pendente; ?>
										<span class="label label-important">Pendente</span>
									<?php endif; ?>
								</td>
								<td>
									<a class="btn btn-danger"  data-toggle="modal" href="#fatura-pagamentos-<?php echo $fatura['idFatura']; ?>">Pagamentos</a>
									<a class="btn btn-success" href="/aluno/index/fatura/idFatura/<?php echo $fatura['idFatura']; ?>">
										<img src="/images/icons/small/white/download.png" width="20px;">
									</a>
								</td>
							</tr>
						<?php endforeach; ?>

					</table>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="span12">

		</div>
	</div>

</div>
