<?php $this->headTitle('Início'); ?>

		<h4><a href="<?php echo $this->url(array(
				'module'	=>	'aluno',
				'controller'=>	'index',
				'action'	=>	'boletim'),null,1);?>">Boletim</a></h4>
				
		<h4><a href="<?php echo $this->url(array(
				'module'	=>	'aluno',
				'controller'=>	'index',
				'action'	=>	'turma'), null, 1);?>">Material</a></h4>		
				
		<h4><a href="<?php echo $this->url(array(
				'module'	=>	'aluno',
				'controller'=>	'index',
				'action'	=>	'altera-senha'),null,1);?>">Alterar Senha</a></h4>

		<h4><a href="<?php echo $this->url(array(
				'module'	=>	'aluno',
				'controller'=>	'index',
				'action'	=>	'historico'),null,1);?>">Histórico</a></h4>