<?php $this->headTitle('Matérial de Aulas'); ?>

<div class="grid_16">
	<div class="page-header">
		<h2>
			Matérial das Aulas de <?php echo $this->row->findParentRow('Application_Model_DbTable_Disciplina')->Disciplina; ?>
		</h2>
	</div>

<br />

<?php if(!empty($this->rows['Nome'])){?>

	<table class="table table-striped data-table">
		<thead>
			<tr>
				<th><font size="3" color="black"><strong>#</strong></font></th>
				<th style="text-align: center;"><font size="3" color="black"><strong>Data da Publicação</strong></font></th>
				<th style="text-align: center;"><font size="3" color="black"><strong>Matérial</strong></font></th>
				<th style="text-align: center;"><font size="3" color="black"><strong>Ação</strong></font></th>
			</tr>
		</thead>
		<tbody>
		<?php foreach($this->rows as $lista){?>
			<tr style="background: #EEE;">
				<td style="width: 50px;"><strong><?php echo $lista->idArquivos; ?></strong></td>
				<td style="width: 300px; text-align: center;"><strong><?php echo $lista->Data; ?></strong></td>
				<td style="width: 250px; text-align: center;"><strong><?php echo $lista->Nome; ?></strong></td>
				<td style="text-align: center;">
					<a id="btn-turma" class="btn btn-success" href="<?php echo $this->url(
						array(
							'controller'	=>	'index',
							'action'		=>	'download',
							'idArquivo'		=>	$lista->idArquivos
						));?>">
							Download	
					</a>
				</td>
			</tr>		
	<?php }
}else{
		echo '<h4>' . 'Nenhum matérial disponível no momento!' . '</h4>';
	}
	?>
	</tbody>
</table>

	<br /><br />
	
</div>