<?php $this->headTitle('Matérial de Aulas');?>

<div class="grid_16">
	<div class="page-header">
		<h2>
			Lista de turmas que há matérial de aulas disponíveis
		</h2>
	</div>
	
	<br /><br />	
	
	<?if(!empty($this->rows['Nome'])){?>
	
	<table class="table table-striped data-table" style="margin-bottom:0;">
		<thead>
			<tr>
				<th><h5>#</h5></th>
				<th><h5>Turma</h5></th>
				<th><h5>Ação</h5></th>
			</tr>
		</thead>
		<tbody>
	
		<?foreach($this->rows as $lista){?>
			<?foreach($this->file as $file){?>
				<?if($file->Disciplina_idDisciplina == $lista->findParentRow('Application_Model_DbTable_Turma')->Disciplina_idDisciplina){?>
					<tr>
						<td><strong><?= $lista->findParentRow('Application_Model_DbTable_Turma')->Disciplina_idDisciplina;?></strong></td>
						<td><strong><?= $lista->findParentRow('Application_Model_DbTable_Turma')->Nome;?></strong></td>
						<td>
							<a class="btn btn-primary" href="<?php echo $this->url(
								array(
									'controller'	=>	'index',
									'action'		=>	'material',
									'idDisciplina'	=>	$lista->findParentRow('Application_Model_DbTable_Turma')->Disciplina_idDisciplina
								));?>">
								Exibir
							</a>
						</td>
					</tr>

				<? }
				}
			}?>
		</tbody>
	</table>
	
	<?
	}
	else{
		echo '<h4>'. 'Não há matérial disponível até o momento' . '</h4>';	
	}?>	
	
	
	<br /><br />
	
</div>