<?php echo $this->partial("_header.phtml"); ?>
	<div id="pjax">
		<div id="wrapper" data-adminica-nav-top="1" data-adminica-side-top="1" class="has_fixed_bar">
			<?php echo $this->partial('components/topbar.php'); ?>
			<?php echo $this->partial('components/sidebar.php'); ?>
			<?php echo $this->partial('components/stackbar.php'); ?></div><!-- Closing Div for Stack Nav, you can boxes under the stack before this -->

			<?php echo $this->partial('components/navbar-fixed.php'); ?>
			<div id="main_container" class="main_container container_16 clearfix">
				<?php //echo $this->partial('components/navigation.php'); ?>
				<?php //echo $this->partial("components/breadcrumb.php"); ?>
				<div class="grid_16">
				  	<div class="page-header">
					    <h1>Grid System
						    <small>960 fluid grid system<small>
					    </h1>
				  	</div>
				  	<p>Adminica uses the 960 fluid grid system but it also includes the default Bootstrap grid system. For info <strong>check out the <a href="http://twitter.github.com/bootstrap/">Bootstrap Documentation</a></strong>.</p>	
				</div>			

			<?php echo $this->layout()->content; ?>

			</div>
		<?php echo $this->partial('dialogs/dialog_welcome.php'); ?>
		<?php echo $this->partial('dialogs/dialog_logout.php'); ?>
<?php echo $this->partial("_footer.phtml"); ?>
