<?php $this->headTitle('Listagem de Turmas'); ?>

<div class="grid_16">
  	<div class="page-header">
	    <h1>Turmas Cadastradas
		    <small>Veja toda a lista das turmas cadastradas</small>
	    </h1>
  	</div>
  	<table class="table table-striped data-table" style="margin-bottom:0;">
	    <thead>
	      <tr>
	        <th><h5>#</h5></th>
	        <th><h5>Turma</h5></th>
	        <th><h5>Ano/Semestre</h5></th>
	        <th><h5>Professor</h5></th>
	        <th><h5>Ações</h5></th>
	      </tr>
	    </thead>
	    <tbody>
<?php foreach ($this->rows as $lista) { ?>
	<tr>
		<td><strong><?php echo $lista->idTurma; ?></strong></td>
		<td><strong><?php echo $lista->Nome; ?></strong></td>
		<td><strong><?php echo $lista->Ano . '.' . $lista->Semestre; ?></strong></td>
		<td><strong><?php echo $lista->findParentRow('Application_Model_DbTable_Usuario')->Nome; ?></strong></td>
		<td>
			<a class="btn btn-primary" href="<?php echo $this->url(
				array(
					'controller'	=>	'turma',
					'action'		=>	'editar',
					'idTurma'		=>	$lista->idTurma
				));
				?>">
				Editar
			</a>
	
			<a class="btn btn-warning" href="<?php echo $this->url(
				array(
					'controller'	=>	'turma',
					'action'		=>	'delete',
					'idTurma'		=>	$lista->idTurma
				));
				?>">
				Excluir
			</a>
		</td>
	</tr>
	
<?php }?> <!-- fim foreach -->
</table>

	<br /><br />
</div>