<table class="table table-bordered">
    <thead>
    <tr>
        <th style="width:350px;" >Alunos</th>
        <th style="width:100px; text-align: center;" >Faltas</th>
        <th style="width:100px; text-align: center;" >Média</th>
        <th style="width:100px; text-align: center;" >Situação</th>
    </tr>
    </thead>
    <tbody>
    <?php
    $total = 0;
    $id = $this->turma_id;
    $matric = new Application_Model_DbTable_Matricula();
    $dados = $matric->findForSelect($id);
    foreach($dados as $nomes) :
    $nota = new Application_Model_DbTable_Nota();
    $presenca = new Application_Model_DbTable_Presenca();
    $idUsuario = $nomes->idUsuario_has_Turma;
    $media = $nota->media($idUsuario);
    $chamada = $presenca->contaPresenca($idUsuario);
    ?>
    <tr>
        <td><?php echo $nomes->findParentRow('Application_Model_DbTable_Usuario')->Nome; ?></td>
        <?php if($chamada["SUM(Faltas)"] != null){?>
        <td style="text-align: center; "><?php echo $chamada["SUM(Faltas)"]; ?></td>
        <?php }
									else{?>

        <td style="text-align: center; "><?php echo " - "; ?></td>

        <?php }?>
        <?php if($media < 7){ ?>
        <td style="text-align: center; color:red; "><?php echo number_format($media, 1,',','.'); ?></td>
        <?php } else { ?>
        <td style="text-align: center; "><?php echo number_format($media, 1,',','.'); ?></td>
        <?php } ?>
        <td style="text-align: center; ">
            <?php switch ($nomes->Status){
            case 'Aprovado':
            echo "<span class='label label-success'>$nomes->Status</span>";
            break;
            case 'Reprovado':
            echo "<span class='label label-important'>$nomes->Status</span>";
            break;
            case 'Cursando':
            echo "<span class='label label-info'>$nomes->Status</span>";
            break;
            } ?>
        </td>
    </tr>
    <?php $total++;?>
    <?php endforeach; ?>
    <tr>
        <th>Total de Alunos Matrículados &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo  $total; ?></th>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    </tbody>
</table>