<?php $this->headTitle('Fatura')?>
<div class="grid_16">

	<?php 
	header("Content-type:text/html; charset=utf-8");
	ob_start();	
	?>
	
	<table>
		<tr>
			<th><img src="/images/logosibb2.gif" height="120px" width="120px"></th>
			<th width="550px">
				<font size="5">SEMINÁRIO E INSTITUTO BATISTA BEREIANO</font>
				<p><font size="3">Rua Mar do Leste, 100, Pajuçara - CEP: 59.133-380 / Natal-RN</font></p>
				<font size="3">Email: <font color="blue">contato@seminariobereiano.com.br</font></font>
				<p><font size="3">Fone: (084) 3221-2520 / 3201-0083</font></p>
			</th>
		</tr>
	</table>
	
	<hr />
	
	<?php foreach($this->rows as $fatura){
		$id = $fatura['Usuario_idUsuario'];
		
	}?>
	
	<br />
	
	<?php foreach($fatura['debitos'] as $lista){
			if($lista['type'] == 'servico'){
				$matricula = $lista['servico']['nome_servico'] == 'Taxa de Matrícula';
			}
		}
			
		if(isset ($matricula)){
			echo '<h3 style="text-align: center">' . 'Fatura Referente a Matrícula' . '</h3>';
		}
		else{
		
			echo '<h3 style="text-align: center">' . 'Extrato de Conta do Mês de ';
			switch ($fatura['mes']){
				case 1 :
					echo ' Janeiro';
					break;
				case 2 :
					echo ' Fevereiro';
					break;
				case 3 :
					echo ' Março';
					break;
				case 4 :
					echo ' Abril';
					break;
				case 5 :
					echo ' Maio';
					break;
				case 6 :
					echo ' Junho';
					break;
				case 7 :
					echo ' Julho';
					break;
				case 8 :
					echo ' Agosto';
					break;
				case 9 :
					echo ' Setembro';
					break;
				case 10 :
					echo ' Outubro';
					break;
				case 11 :
					echo ' Novembro';
					break;
				case 12 :
					echo ' Dezembro';
					break;
			}
			echo '</h3>';
		}
	?>
	
	
	<br />

	<strong>Nome: <?php foreach($fatura['usuario'] as $usuario){ echo $usuario['Nome']; } ?></strong>
	
	<br /> <br /> <br />
	
	<table cellpadding="5px" cellspacing="0" style="border-collapse: collapse; ">
		<thead>
			<tr>
				<th style="text-align:center;">Cód.</th>
				<th style="text-align:left;">Descrição do Item</th>
				<th style="text-align:center;">Quantidade</th>
				<th style="text-align:center;">Valor Unit.</th>
				<th style="text-align:center;">Total</th>
			</tr>
		</thead>
		
		<tbody>
		
		<?php $i = 0; ?>
		<?php $valor_total = 0; ?>
		
			<?php foreach($fatura['debitos'] as $debito) : ?>
			<tr <?php if($i % 2 == 0) : ?> style="background: #F1F1F1 "<?php endif;?>>
				<td style="text-align: center; width: 40px;"><?php echo $debito['idDebitos']; ?>
				<td style="text-align: left; width: 400px;">
					<?php
						if ( $debito['type'] == 'servico' ) {
							$desc_debito = $debito['servico']['nome_servico'];
						} else if ( $debito['type'] == 'matricula' ) {
							$desc_debito = $debito['matricula']['nome_turma'] . ' - ' . 
							" {$debito['matricula']['ano_turma']}.{$debito['matricula']['semestre_turma']}";
						}
						echo $desc_debito;
					?>
				</td>
				<td style="text-align: center; width: 120px;">
					<?php
						if ( $debito['type'] == 'servico' ) {
							$desc_debito = $debito['servico']['qtd_servico'];
						} else if ( $debito['type'] == 'matricula' ) {
							$desc_debito = $debito['matricula']['qtd_creditos'];
						}
						echo $desc_debito;
					?>
				</td>
				<td style="text-align: center; width: 100px;">
					R$
					<?php
						if ( $debito['type'] == 'servico' ) {
							$valor = $debito['servico']['valor_cobrado_servico'];
						} else if ( $debito['type'] == 'matricula' ) {
							$config = new Application_Model_DbTable_Configs();
							$valor_cred = $config->findKey('valor_credito');
							$valor = $valor_cred;
						}
						echo number_format($valor,2,',','.');
					?>
				</td>
				<td style="text-align: center; width: 120px;">
					R$
					<?php
						
						if ( $debito['type'] == 'servico' ) {
							$valor = $debito['servico']['valor_cobrado_servico'];
						} else if ( $debito['type'] == 'matricula' ) {
							$valor = $debito['matricula']['valor_cobrado'];
						}
						
						echo number_format($valor,2,',','.');
						$valor_total += $valor;
					?>
				</td>
			</tr>
			
			<?php endforeach; ?>		
			
		</tbody>
	</table>
	<div style="margin: 10px 0 0 340px; font-size: 13px;">
	
	<?php
		$idFatura = $fatura['idFatura'];
		$valor_total_pagamentos = 0;
		$pagamentos_model = new Application_Model_DbTable_Pagamento();
		$pagamentos = $pagamentos_model->listar($fatura['idFatura']);
		$pega_data = $pagamentos_model->pegaData($idFatura);
		
	?>
		<h4>
			<?php $count = 0?>
			
			<?php foreach($pagamentos as $pagamento) : ?>
					<?php $count += count($pagamento->valorPagamento);?>
					
					<?php $valor_total_pagamentos += $pagamento->valorPagamento; ?>
			<?php endforeach; ?>
			
			<?php $valor_descontado = $valor_total - ($valor_total * $fatura['desconto']/100); ?>
			<?php $valor_restante = $valor_descontado - $valor_total_pagamentos; ?>
			
			<!-- Imprime a fatura que ainda não tem nenhum pagamento -->
			
			<?php if(! isset ($pagamento)){?>
			
			
				SubTotal:	<div style="margin-top: -19px; padding-bottom: 3px; text-align: right;"><?php echo 'R$ ' . number_format($valor_total,2,',','.'); ?></div>
				
				Descontos:	   <div style="margin-top: -19px; padding-bottom: 3px; text-align: right;"><?php echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;' . number_format($fatura['desconto']) . '%'; ?> </div>
			
				Total a Pagar: <div style="margin-top: -19px; padding-bottom: 3px; text-align: right;"><?php echo 'R$ ' . number_format($valor_total,2,',','.'); ?></div>
				
			<?php } ?>
			
			<!--  Imprime a fatura que foi feito apenas um pagamento e o foi o valor total da fatura -->
			
			<?php if(isset($pagamento) && $valor_total == $valor_total_pagamentos){?>
				
				SubTotal:	<div style="margin-top: -19px; padding-bottom: 3px; text-align: right;"><?php echo 'R$ ' . number_format($valor_total,2,',','.'); ?></div>
				
				Descontos:	   <div style="margin-top: -19px; padding-bottom: 3px; text-align: right;"><?php echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;' . number_format($fatura['desconto']) . '%'; ?> </div>
			
				Total a Pagar: <div style="margin-top: -19px; padding-bottom: 3px; text-align: right;"><?php echo 'R$ ' . number_format($valor_total,2,',','.'); ?></div>

				<?php	// $recebido = count($pagamento['valorPagamento']); ?>
				
				<?php if($count >= 2){?>
					Total Recebido: <div style="margin-top: -19px; padding-bottom: 3px; text-align: right;"><?php echo 'R$ ' . number_format($pagamento->valorPagamento,2,',','.'); ?></div>
					
					Data de Pagamento: <div style="margin-top: -19px; padding-bottom: 3px; text-align: right;">
			
					<?php foreach($pega_data as $data) :
								echo date('d/m/Y', strtotime($data['dataPagamento'])); ?>
			  		<?php endforeach; ?>	
				</div>
				<br />
				Valor Total Acumulado: <div style="margin-top: -19px; padding-bottom: 3px; text-align: right;"><?php echo 'R$ ' . number_format($valor_total_pagamentos,2,',','.');?> </div>
				
						<?php if(isset($pagamento['idPagamento'])) : ?>
					<?php if($valor_restante == 0){ ?>
						<br />
						<div style="margin-top: -19px; color: #FF1C3A; padding-bottom: 3px; text-align: right;">PAGO!</div>
					<?php } else { ?>
						
						Valor Total Restante: <div style="margin-top: -19px; color: #FF1C3A; padding-bottom: 3px; text-align: right;"> 
							R$ <?php echo number_format($valor_restante,2,',','.');?>
							</div>
					<?php } ?>
				<?php endif; ?>
					
					
				<?php } else {?>
				Total Recebido: <div style="margin-top: -19px; padding-bottom: 3px; text-align: right;">  
							R$ 	<?php //foreach($pagamentos as $pagamento) : ?>
									<?php //$valor_total_pagamentos += $pagamento->valorPagamento; ?>
								<?php //endforeach; ?>
								
								<?php echo number_format($valor_total_pagamentos,2,',','.');?> </div>
				Data de Pagamento: <div style="margin-top: -19px; padding-bottom: 3px; text-align: right;">
		
					<?php if(! isset($pagamento['dataPagamento'])){
							echo ' ';
			  		} else {	
						foreach($pega_data as $data) :
							echo date('d/m/Y', strtotime($data['dataPagamento'])); ?>
		  			<?php endforeach; }?>	
				</div>
				
				<?php } ?>
				
			<!-- Imprime a fatura que está sendo paga em partes -->
			
			<?php } ?>

			<?php if(isset($pagamento) && $valor_total != $valor_total_pagamentos){?>
			
				SubTotal:	<div style="margin-top: -19px; padding-bottom: 3px; text-align: right;"><?php echo 'R$ ' . number_format($valor_total,2,',','.'); ?></div>
				
				Descontos:	   <div style="margin-top: -19px; padding-bottom: 3px; text-align: right;"><?php echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;' . number_format($fatura['desconto']) . '%'; ?> </div>
			
				Total a Pagar: <div style="margin-top: -19px; padding-bottom: 3px; text-align: right;"><?php echo 'R$ ' . number_format($valor_total,2,',','.'); ?></div>
				
				Total Recebido: <div style="margin-top: -19px; padding-bottom: 3px; text-align: right;"><?php echo 'R$ ' . number_format($pagamento->valorPagamento,2,',','.'); ?></div>  
							<?php //foreach($pagamentos as $pagamento) : ?>
									<?php //$valor_total_pagamentos += $pagamento->valorPagamento; ?>
								<?php //endforeach; ?>
								
				Data de Pagamento: <div style="margin-top: -19px; padding-bottom: 3px; text-align: right;">
			
					<?php foreach($pega_data as $data) :
								echo date('d/m/Y', strtotime($data['dataPagamento'])); ?>
			  		<?php endforeach; ?>	
				</div>
				<br />
				Valor Total Acumulado: <div style="margin-top: -19px; padding-bottom: 3px; text-align: right;"><?php echo 'R$ ' . number_format($valor_total_pagamentos,2,',','.');?> </div>
				
						<?php if(isset($pagamento['idPagamento'])) : ?>
					<?php if($valor_restante == 0){ ?>
						<br />
						<div style="margin-top: -19px; color: #FF1C3A; padding-bottom: 3px; text-align: right;">PAGO!</div>
					<?php } else { ?>
						
						Valor Total Restante: <div style="margin-top: -19px; color: #FF1C3A; padding-bottom: 3px; text-align: right;"> 
							R$ <?php echo number_format($valor_restante,2,',','.');?>
							</div>
					<?php } ?>
				<?php endif; ?>
				
			<?php  } ?>
				<br />
							
		<br />
		
		</h4>
	</div>
	<?php 
	//die; 
	$html = ob_get_contents();
	ob_end_clean();
	
	define('MPDF_PATH', APPLICATION_PATH . '/../library/mpdf/');
	
	include(MPDF_PATH .'mpdf.php');
	
	$mpdf = new mPDF('pt', 'A4', 11);
	
	$mpdf->allow_charset_conversion = true;
	$mpdf->charset_in = 'utf-8';
	
	$mpdf->SetDisplayMode('fullpage');
	//$mpdf->SetHeader('Seminário e Instituto Batista Bereiano - Extrato de Conta');
	$mpdf->SetFooter('Fatura gerada no dia {DATE j/m/Y} | {PAGENO}');
	$mpdf->WriteHTML($html);
	//$mpdf->AddPage();
	//$mpdf->WriteHTML($html);
	
	foreach($fatura['usuario'] as $usuario){ $nome =  $usuario['Nome']; }
	
	$arquivo = 'Fatura ' . ' - ' . $nome . '.pdf';
	
	$mpdf->Output($arquivo, 'D');
	
	exit();
	
	?>
	
</div>