<?php $this->headTitle('Faturas'); ?>

<div class="grid_16">
	<div class="page-header">
		<h1>Faturas - 
			<small>Visualize todas as Faturas</small>
		</h1>
	</div>


	<div class="row">
		<div class="span12">

			<form action="/admin/faturas" method="GET" class="row">
				<fieldset class="span12">

					<legend>Escolha o Aluno</legend>
					<select class="sibb-select2 " id="aluno" style="width:200px" name="aluno">
						<option value="-1">Todos</option>
						<?php
						$users = new Application_Model_DbTable_Usuario();
						$users = $users->fetchAll();
						foreach ($users as $user) :
							?>
							<option <?php if ( $user->idUsuario == $this->user_id) echo 'selected' ?> value="<?= $user->idUsuario; ?>"><?= $user->Nome; ?></option>
						<?php endforeach; ?>
					</select>


					<input type="submit" value="Filtrar" class="btn btn-danger span2" />

				</fieldset>


			</form>
		</div>
	</div>

		
	<table class="table table-striped" style="margin-bottom:0;">
		<thead style="color: #000; font-size: 13px; font-weight: 700; font-family: Georgia; ">
			<tr>
				<th>#</th>
				<th style="text-align: left;">Aluno</th>
				<th style="text-align: center;">Mês/Ano</th>
				<th style="text-align: center;">Qtd Débitos</th>
				<th style="text-align: center;">Valor</th>
				<th style="text-align: center;">Desconto na Fatura</th>
				<th style="text-align: center;">à pagar</th>
				<th style="text-align: center;">Status</th>
				<th style="text-align: center;">Ações</th>

			</tr>
		</thead>
		
		<tbody style="font-weight: 700; font-size: 12px;">
	<?php foreach ($this->rows as $fatura){ ?>
		<tr>
			<td style="text-align: center; width: 10px;">
				<strong><?php echo $fatura['idFatura']; ?></strong>
				<div class="modal hide fade" id="fatura-pagamentos-<?php echo $fatura['idFatura']; ?>">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
						<span style="color: #000; font-size: 20px; font-weight: 700; font-family: Georgia; ">
							Listagem de pagamentos da Fatura #
								<span style="font-family: Liberation-Serif;">
									<?php echo $fatura['idFatura']; ?>
								</span>
						</span>
					</div>
					<div class="modal-body">
						<table class="table table-striped">
							<thead style="color: #000; font-size: 13px; font-weight: 700; font-family: Georgia; ">
							<tr>
								<th style="text-align: center;">#</th>
								<th style="text-align: center;">Valor Pago</th>
								<th style="text-align: center;">Data</th>
								<th style="text-align: center;">Observações</th>
								<th style="text-align: center;">Ações</th>
							</tr>
							</thead>
							<tbody>
							<?php
							$valor_total_pagamentos = 0;
							$total_restante = 0;
							$pagamentos_model = new Application_Model_DbTable_Pagamento();
							$pagamentos = $pagamentos_model->listar($fatura['idFatura']);
							foreach($pagamentos as $pagamento) : ?>
								<tr>
									<td style="width: 10%; text-align: center;">	<?php echo $pagamento->idPagamento; ; ?>
									</td>
									<td style="width: 20%; text-align: center;">
										R$ <?php echo number_format($pagamento->valorPagamento,2,',','.'); $valor_total_pagamentos += $pagamento->valorPagamento; ?>
									</td>
									<td style="width: 20%; text-align: center;">	<?php echo date('d/m/Y', strtotime($pagamento->dataPagamento)); ?>
									</td>
									<td style="width: 30%; text-align: center;">	<?php echo $pagamento->Descricao; ?>
									</td>
									<td style="width: 20%; text-align: center;">
										<a class="btn btn-warning" href="<?php echo $this->url(
											array(
												'controller'	=>	'pagamento',
												'action'		=>	'delete',
												'idPagamento'	=>	$pagamento->idPagamento,
												'idUsuario'     =>  $fatura['debitos'][0]['user']['idUsuario']
											));?>">
											Excluir
										</a>
									</td>
								</tr>
								
							<?php endforeach; ?>
							<tr>
								<td>Total: </td>
								<td>R$ <?php echo number_format($valor_total_pagamentos,2,',','.'); ?>
								</td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
							
							<?php $valor = $fatura['valorFatura']; ?>
							<?php $valor_pendente = number_format($valor - $valor_total_pagamentos,2); ?>
							<?php if($valor_pendente != 0) { ?>
							<tr>
								<td>
									<span class="label label-important">Restante: 
									</span>
								</td>
								<td>
									<span class="label label-important">R$ <?php echo number_format($valor_pendente,2,',','.'); ?>
									</span>
								</td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
							<?php } else { ?>
							<tr>
								<td>
									<span class="label label-success">Pago</span>
								</td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
							<?php } ?>
							</tbody>
						</table>
					</div>
					<div class="modal-footer">
					<?php if($valor_total_pagamentos != 0) { ?>
						<a style="width: 80px; font-size: 10px; " class="btn btn-primary" title="Baixar Fatura" target="_blank" href="<?php echo $this->url(
							array(
								'controller'	=>	'faturas',
								'action'		=>	'pendente',
								'idFatura'		=>	$fatura['idFatura']
							));?>">
							Imprimir Recibo
						</a>
						
					<?php } ?>
						<a href="#" class="btn" data-dismiss="modal">Fechar</a>
					</div>
				</div>
			</td>
			<td style="width: 20%; text-align: left; "><?php echo $fatura['debitos'][0]['user']['Nome']; ?></td>
			<td style="width: 4%; text-align: center; "><?php echo $fatura['mes'] . '/' . $fatura['ano']; ?></td>
			<td style="width: 3%; text-align: center; "><?php echo count($fatura['debitos']); ?></td>

			<td style="width: 7%; text-align: center; ">R$ <?php echo number_format($valor,2,',','.'); ?></td>
			<td style="width: 4%; text-align: center; "><?php echo $fatura['desconto']; ?> % </td>
			<td style="width: 7%; text-align: center; ">
				
				<?php $pago = ( $valor_pendente <= 0) ? true : false; ?>
				
				<?php if($valor_pendente == $fatura['valorFatura']){
						$total_apagar = $valor - ($valor * $fatura['desconto']/100); echo 'R$ ' . number_format($total_apagar,2,',','.');
				} else {
					echo 'R$ ' . number_format($valor_pendente,2,',','.');
				}
				
				?>
				
			</td>
			<td style="width: 5%; text-align: center; font-size: 10px;">
				<strong>
					<?php if ( $pago ) : ?>
					<span class="label label-success">Pago</span>
					<?php else: ?>
					<span class="label label-important">Pendente</span>
					<?php endif; ?>
				</strong>
			</td>
			<td  style="width: 50%">
				<a style=" width: 63px; color: black; font-size:10px;" class="btn btn-info" data-toggle="modal" href="#fatura-desc-<?php echo $fatura['idFatura']; ?>">
					Detalhamento
				</a>
				<?php if ( ! $pago ) : ?>
					<a style="font-size: 10px; width:93px;" class="btn btn-inverse" data-toggle="modal" href="#fatura-add-pagamento-<?php echo $fatura['idFatura']; ?>">Efetuar Pagamento
					</a>
				<?php endif; ?>
				<a style="font-size: 10px; width: 81px;" class="btn btn-danger"  data-toggle="modal" href="#fatura-pagamentos-<?php echo $fatura['idFatura']; ?>">Ver Pagamentos</a>
				<?php if ( $valor_total_pagamentos == 0 ) :?>
					<a style="font-size:10px; width:25px;" class="btn btn-default" href="<?php echo $this->url(
						array(
							'controller'	=>	'faturas',
							'action'		=>	'editar',
							'idFaturas'		=>	$fatura['idFatura']
						));?>">
							Editar
					</a>

					<a style="font-size:10px; width:29px;" class="btn btn-warning" href="<?php echo $this->url(
						array(
							'controller'	=>	'faturas',
							'action'		=>	'delete',
							'idFaturas'		=>	$fatura['idFatura']
						));?>">
							Excluir
					</a>
				<?php endif; ?>
				
						<a style="width: 17px;" class="btn btn-success" title="Baixar Fatura" href="<?php echo $this->url(
							array(
								'controller'	=>	'faturas',
								'action'		=>	'download',
								'idFatura'		=>	$fatura['idFatura']
							));?>">
							<img src="/images/icons/small/white/download.png" width="20px;">
						</a>
				
				<div class="modal hide fade" id="fatura-desc-<?php echo $fatura['idFatura']; ?>">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
						<span style="color: #000; font-size: 20px; font-weight: 700; font-family: Georgia; ">
							Detalhes da Fatura
						</span>
					</div>
					<div class="modal-body">
						<table class="table table-striped">
							<thead style="color: #000; font-size: 14px; font-weight: 700; font-family: Georgia;">
								<tr>
									<th style="text-align: center;">#</th>
									<th style="text-align: center;">Descrição</th>
									<th style="text-align: center;">Mês/Ano</th>
									<th style="text-align: center;">Valor</th>
								</tr>
							</thead>
							<tbody style="font-size: 11px;">
							<?php
							$valor_total = 0;
							foreach($fatura['debitos'] as $debito) : ?>
								<tr>
									<td style="width: 5%; text-align: center;">	<?php echo $debito['idDebitos']; ?>
									</td>
									<td style="width: 60%">
										<?php
										$desc_debito = '';
										$valor_cobrado = 0;
										if ( $debito['type'] == 'servico' ) {
											$desc_debito = "Serviço: " . $debito['servico']['nome_servico'] . ' - ' . $debito['servico']['descricao_servico'];
										} else if ( $debito['type'] == 'matricula' ) {
											$desc_debito = $debito['matricula']['nome_turma'] .
												" ({$debito['matricula']['disciplina']}) {$debito['matricula']['ano_turma']}.{$debito['matricula']['semestre_turma']}";

										}
										echo $desc_debito;
										?>
									</td>
									<td style="width: 10%; text-align: center;">
										<?php echo $debito['mesPagamento'] .'/' . $debito['anoPagamento'];?>
									</td>
									<td style="width: 20%; text-align: center;">
										R$
										<?php
										$valor = $debito[$debito['type']]['valor_final'];
										echo number_format($valor,2) . " (" . $debito['descontoMes'] . "%)";
										$valor_total += $valor;
										?></td>
								</tr>
							<?php endforeach; ?>
							</tbody>
						</table>
					</div>
					<div class="modal-footer">
						<a href="#" class="btn" data-dismiss="modal">Fechar</a>
					</div>
				</div>
				<div class="modal hide fade" id="fatura-add-pagamento-<?php echo $fatura['idFatura']; ?>">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
						<span style="color: #000; font-size: 20px; font-weight: 700; font-family: Georgia; ">
							Adicionar Pagamento a Fatura <span style="font-family: Liberation-Serif;">#<?php echo $fatura['idFatura']; ?></span>
						</span>
					</div>
					<form action="/admin/pagamento/addpagamento" class="form-horizontal" method="POST">
						<div class="modal-body">
							
							<p style="text-align: center; font-size: 15px; font-weight: 700; font-family: Liberation-Serif; ">
								<?php if($valor_pendente == $fatura['valorFatura']){ echo 'Valor da Fatura: ' . 'R$ ' . number_format($total_apagar,2,',','.'); } else{ echo 'Valor Pendente da Fatura: ' . number_format($valor_pendente,2,',','.'); }?>
							<p>
							
							<hr />
							<div class="control-group">
								<label style="font-family: Liberation-Serif; font-size: 14px;" class="control-label" for="data">
									Data: 
								</label>
								<div class="controls">
									<input style="font-family: Liberation-Serif; font-size: 14px;" type="date" placeholder="Data" name="data" class="input-medium" required/>
								</div>
							</div>
							<div class="control-group">
								<label style="font-family: Liberation-Serif; font-size: 14px;" class="control-label" for="valor">
									Valor
								</label>
								<div class="controls">
									<div class="input-prepend">
										<span class="add-on">R$</span>
										<input style="font-family: Liberation-Serif; font-size: 14px;" type="text" class="input-small" name="valor" placeholder="Valor" required/>
									</div>
								</div>
							</div>
							<div class="control-group">
								<label style="font-family: Liberation-Serif; font-size: 14px;" class="control-label" for="descricao">
									Observações
								</label>
								<div class="controls">
									<label class="controles">
										<textarea style="font-family: Liberation-Serif; font-size: 14px;" name="descricao"  cols="30" rows="10"></textarea>
									</label>
								</div>
							</div>


							<input type="hidden" name="idFatura" value="<?php echo $fatura['idFatura'] ?>" />
							<input type="hidden" name="user_id" value="<?php echo $fatura['debitos'][0]['user']['idUsuario']; ?>" />
						</div>
						<div class="modal-footer">
							<input type="submit" class="btn btn-primary" value="Adicionar" />
							<a href="#" class="btn" data-dismiss="modal">Fechar</a>
						</div>
					</form>
				</div>
			</td>
		</tr>

	<?php }?>
		</tbody>
	</table>

	<?php 

		$start = (isset($_GET['start']))? $_GET['start'] : 0;
		$pagina = (isset($_GET['pagina'])) ? $_GET['pagina'] : 1;
		$total = $this->total;
		$per_page = $this->per_page;
		$current_page = $this->page;
		$n_pages = ceil ($total / $per_page);
		$asc = 23;


	?>
	<br />
	<hr style="border: 1px solid #ddd" />
	<br />

	<ul style="font-size: 12px; " class="pagination">
    
	<?php

		for ( $ipage = $pagina; $ipage <= $n_pages - $asc; $ipage++) {
			
			if($ipage >= 1){


				if ( $start == $per_page * ( $ipage - 1 )) {
				echo sprintf(
					'<li style="margin: 0 2px; font-weight: 700;
								float: left; padding: 9px 16px;
								text-decoration: none; 
								background-color: #4CAF50;
								color: white;
								border-radius: 5px;" class="pagination_active">'. 
								$ipage .
					'</li>');
				} else {
					echo sprintf(
					'<li style="margin: 0 2px; color: black;
							float: left; border-radius: 5px;"
							class="pagination">
					<a style="text-align: center;"	href="%s"> %d </a></li>',
					$this->url(
							array(
								'controller'=> 'faturas',
								'action' 	=> 'index',
							)
						) . '?start=' . $per_page * ( $ipage - 1 ) . '&length=' . $per_page,
						$ipage
					);
				}
			}
		}
	?>

	</ul>

	<br /><br /><br /><br /><br /><br />
	
</div>