<?php $this->headTitle('Faturas'); ?>

<div class="grid_16">
	<div class="page-header">
		<h1>Faturas - 
			<small>Visualize todas as Faturas</small>
		</h1>
	</div>


	<div class="row">
		<div class="span12">

			<form action="/admin/faturas" method="GET" class="row">
				<fieldset class="span12">

					<legend>Escolha o Aluno</legend>
					<select class="sibb-select2 " id="aluno" style="width:200px" name="aluno">
						<option value="-1">Todos</option>
						<?php
						$users = new Application_Model_DbTable_Usuario();
						$users = $users->fetchAll();
						foreach ($users as $user) :
							?>
							<option <?php if ( $user->idUsuario == $this->user_id) echo 'selected' ?> value="<?= $user->idUsuario; ?>"><?= $user->Nome; ?></option>
						<?php endforeach; ?>
					</select>


					<input type="submit" value="Filtrar" class="btn btn-danger span2" />

				</fieldset>


			</form>
		</div>
	</div>

		
	<table class="table table-striped data-table" style="margin-bottom:0;">
		<thead>
			<tr>
				<th><h5><strong>#</strong></h5></th>
				<th style="text-align: left;"><h5>Aluno</h5></th>
				<th style="text-align: center;"><h5>Mês/Ano</h5></th>
				<th style="text-align: center;"><h5>Qtd Débitos</h5></th>
				<th style="text-align: center;"><h5>Valor</h5></th>
				<th style="text-align: center;"><h5>Desconto na Fatura</h5></th>
				<th style="text-align: center;"><h5>A pagar</h5></th>
				<th style="text-align: center;"><h5>Status</h5></th>
				<th style="text-align: center;"><h5>Ações</h5></th>

			</tr>
		</thead>
		
		<tbody>
	<?php foreach ($this->rows as $fatura){ ?>
		<tr>
			<td style="text-align: center; width: 10px;">
				<strong><?php echo $fatura['idFatura']; ?></strong>
				<div class="modal hide fade" id="fatura-pagamentos-<?php echo $fatura['idFatura']; ?>">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
						<h3>Listagem de pagamentos da Fatura #<?php echo $fatura['idFatura']; ?></h3>
					</div>
					<div class="modal-body">
						<table class="table table-striped">
							<tr>
								<th style="width: 10px; text-align: left;">#</th>
								<th style="text-align: center;">Valor Pago</th>
								<th style="text-align: center;">Data</th>
								<th style="text-align: center;">Valor Restante</th>
								<th style="text-align: center;">Observações</th>
								<th style="text-align: center;">Ações</th>
							</tr>
							<tbody>
							<?php
							$valor_total_pagamentos = 0;
							$total_restante = 0;
							$pagamentos_model = new Application_Model_DbTable_Pagamento();
							$pagamentos = $pagamentos_model->listar($fatura['idFatura']);
							foreach($pagamentos as $pagamento) : ?>
								<tr>
									<td style="width: 10px; text-align: left;"><?php echo $pagamento->idPagamento; ; ?></td>
									<td style="width: 60px; text-align: center;">
										R$ <?php echo number_format($pagamento->valorPagamento,2,',','.'); $valor_total_pagamentos += $pagamento->valorPagamento; ?>
									</td>
									<td style="width: 30px; text-align: center;"><?php echo date('d/m/Y', strtotime($pagamento->dataPagamento)); ?></td>
									<td style="width: 90px; text-align: center;"><?php $total_fatura = $fatura['valorFatura'] - ($fatura['valorFatura'] * $fatura['desconto']/100); ?>
									 
											<?php $valor_restante = $total_fatura - $pagamento->valorPagamento;?>
											
											<?php if($valor_total_pagamentos == $total_fatura ){ ?>
												<span class="label label-success"><strong>Pago</strong></span>
											<?php } else { ?>
											<span class="label label-important"> R$ <?php echo number_format($valor_restante,2,',','.')?></span>
											<?php } ?>
											
									</td>
									<td style="text-align: center;"><?php echo $pagamento->Descricao; ?></td>
									<td style="width: 30px; text-align: center;">
										<a class="btn btn-warning" href="<?php echo $this->url(
											array(
												'controller'	=>	'pagamento',
												'action'		=>	'delete',
												'idPagamento'	=>	$pagamento->idPagamento,
												'idUsuario'     =>  $fatura['debitos'][0]['user']['idUsuario']
											));?>">
											Excluir
										</a>
									</td>
								</tr>
								
							<?php endforeach; ?>
							<tr>
								<td><strong>Total:</strong></td>
								<td><strong>R$ <?php echo number_format($valor_total_pagamentos,2,',','.'); ?></strong></td>
								<td></td>
								<td></td>
							</tr>
							</tbody>
						</table>
					</div>
					<div class="modal-footer">
						<a href="#" class="btn" data-dismiss="modal">Fechar</a>
					</div>
				</div>
			</td>
			<td style="text-align: left; "><strong><?php echo $fatura['debitos'][0]['user']['Nome']; ?></strong></td>
			<td style="width: 10px; text-align: center; "><strong><?php echo $fatura['mes'] . '/' . $fatura['ano']; ?></strong></td>
			<td style="width: 10px; text-align: center; "><strong><?php echo count($fatura['debitos']); ?></strong></td>

			<td style="width: 65px; text-align: center; "><strong>R$ <?php
					//echo $fatura['valorFatura'] * $fatura['desconto']/100;
					$valor = $fatura['valorFatura'];
					echo number_format($valor,2,',','.');
					?></strong></td>
			<td style="width: 20px; text-align: center; "><strong><?php echo $fatura['desconto']; ?> % </strong></td>
			<td style="width: 55px; text-align: center; "><strong>
				<?php $valor_pendente = number_format($valor - $valor_total_pagamentos,2); ?>
				<?php $pago = ( $valor_pendente <= 0) ? true : false; ?>
				
				<?php if($valor_pendente == $fatura['valorFatura']){
						$total_apagar = $valor - ($valor * $fatura['desconto']/100); echo 'R$ ' . number_format($total_apagar,2,',','.');
				} else {
					echo 'R$ ' . number_format($valor_restante,2,',','.');
				}
				
				?>
				
			</strong></td>
			<td style="width: 10px; text-align: center; font-size: 10px;">
				<strong>
					<?php if ( $pago ) : ?>
					<span class="label label-success">Pago</span>
					<?php else: ?>
					<span class="label label-important">Pendente</span>
					<?php endif; ?>
				</strong>
			</td>
			<td  style="width: 466px;">
				<a style=" width: 63px; color: black; font-size:10px;" class="btn btn-info" data-toggle="modal" href="#fatura-desc-<?php echo $fatura['idFatura']; ?>">
					<strong>Detalhamento</strong>
				</a>
				<?php if ( ! $pago ) : ?>
					<a style="font-size: 10px; width:93px;" class="btn btn-inverse" data-toggle="modal" href="#fatura-add-pagamento-<?php echo $fatura['idFatura']; ?>"><strong>Efetuar Pagamento</strong></a>
				<?php endif; ?>
				<a style="font-size: 10px; width: 81px;" class="btn btn-danger"  data-toggle="modal" href="#fatura-pagamentos-<?php echo $fatura['idFatura']; ?>"><strong>Ver Pagamentos</strong></a>
				<?php if ( $valor_total_pagamentos == 0 ) :?>
					<a style="font-size:10px; width:25px;" class="btn btn-primary" href="<?php echo $this->url(
						array(
							'controller'	=>	'faturas',
							'action'		=>	'editar',
							'idFaturas'		=>	$fatura['idFatura']
						));?>">
							<strong>Editar</strong>
					</a>

					<a style="font-size:10px; width:29px;" class="btn btn-warning" href="<?php echo $this->url(
						array(
							'controller'	=>	'faturas',
							'action'		=>	'delete',
							'idFaturas'		=>	$fatura['idFatura']
						));?>">
							<strong>Excluir</strong>
					</a>
				<?php endif; ?>
					<a style="width: 15px;" class="btn btn-success" title="Baixar Fatura" href="<?php echo $this->url(
						array(
							'controller'	=>	'faturas',
							'action'		=>	'download',
							'idFatura'		=>	$fatura['idFatura']
						));?>">
						
						<img src="/images/icons/small/white/download.png" width="20px;">
					</a>
				
				<div class="modal hide fade" id="fatura-desc-<?php echo $fatura['idFatura']; ?>">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
						<h3>Detalhes da Fatura</h3>
					</div>
					<div class="modal-body">
						<table class="table table-striped">
							<tr>
								<th>#</th>
								<th>Descrição</th>
								<th>Mês/Ano</th>
								<th>Valor</th>
							</tr>
							<tbody>
							<?php
							$valor_total = 0;
							foreach($fatura['debitos'] as $debito) : ?>
								<tr>
									<td><?php echo $debito['idDebitos']; ?></td>
									<td>
										<?php
										$desc_debito = '';
										$valor_cobrado = 0;
										if ( $debito['type'] == 'servico' ) {
											$desc_debito = "Serviço: " . $debito['servico']['nome_servico'] . ' - ' . $debito['servico']['descricao_servico'];
										} else if ( $debito['type'] == 'matricula' ) {
											$desc_debito = 'Matrícula: ' . $debito['matricula']['nome_turma'] .
												" ({$debito['matricula']['disciplina']}) {$debito['matricula']['ano_turma']}.{$debito['matricula']['semestre_turma']}";

										}
										echo $desc_debito;
										?>
									</td>
									<td><?php echo $debito['mesPagamento'] .'/' . $debito['anoPagamento'];?></td>
									<td>
										R$
										<?php
										$valor = $debito[$debito['type']]['valor_final'];
										echo number_format($valor,2) . " (" . $debito['descontoMes'] . "%)";
										$valor_total += $valor;
										?></td>
								</tr>
							<?php endforeach; ?>
							</tbody>
						</table>
					</div>
					<div class="modal-footer">
						<a href="#" class="btn" data-dismiss="modal">Fechar</a>
					</div>
				</div>
				<div class="modal hide fade" id="fatura-add-pagamento-<?php echo $fatura['idFatura']; ?>">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
						<h3>Adicionar Pagamento a Fatura #<?php echo $fatura['idFatura']; ?></h3>
					</div>
					<form action="/admin/pagamento/addpagamento" class="form-horizontal" method="POST">
						<div class="modal-body">
							
							<p style="text-align: center;"><strong><?php if($valor_pendente == $fatura['valorFatura']){ echo 'Valor da Fatura: ' . 'R$ ' . number_format($total_apagar,2,',','.'); } else{ echo 'Valor Pendente da Fatura: ' . number_format($valor_restante,2,',','.'); }?></strong><p>
							
							<hr />
							<div class="control-group">
								<label class="control-label" for="data">Data: </label>
								<div class="controls">
									<input type="date" placeholder="Data" name="data" class="input-medium" required/>
								</div>
							</div>
							<div class="control-group">
								<label class="control-label" for="valor">Valor</label>
								<div class="controls">
									<div class="input-prepend">
										<span class="add-on">R$</span>
										<input type="text" class="input-small" name="valor" placeholder="Valor" required/>
									</div>
								</div>
							</div>
							<div class="control-group">
								<label class="control-label" for="descricao">Observações</label>
								<div class="controls">
									<label class="controles">
										<textarea name="descricao"  cols="30" rows="10"></textarea>
									</label>
								</div>
							</div>


							<input type="hidden" name="idFatura" value="<?php echo $fatura['idFatura'] ?>" />
							<input type="hidden" name="user_id" value="<?php echo $fatura['debitos'][0]['user']['idUsuario']; ?>" />
						</div>
						<div class="modal-footer">
							<input type="submit" class="btn btn-primary" value="Adicionar" />
							<a href="#" class="btn" data-dismiss="modal">Fechar</a>
						</div>
					</form>
				</div>
			</td>
		</tr>

	<?php }?>
		</tbody>
	</table>
	
	<br /><br />
	
</div>