<?php $this->headTitle('Faturas'); ?>

<div class="grid_16">
	<div class="page-header">
		<h1>Cadastrar Faturar
			<small>Preencha o formulário abaixo para cadastrar uma fatura</small>
		</h1>
	</div>
	
	<?php echo $this->form; ?>

	<br />
	<div class=page-header></div>
	<br /><br />
		
	<table class="table table-striped data-table" style="margin-bottom:0;">
		<thead>
			<tr>
				<th>#</th>
				<th>Mês</th>
				<th>Ano</th>
				<th>Desconto</th>
				<th>Valor</th>
				<th>Ações</th>
			</tr>
		</thead>
		
		<tbody>
	<?php foreach ($this->rows as $lista){ ?>
		<tr>
			<td><?php echo $lista->idFatura; ?></td>
			<td><?php echo $lista->mes; ?></td>
			<td><?php echo $lista->ano; ?></td>
			<td><?php echo $lista->desconto; ?></td>
			<td><?php echo $lista->valorFatura; ?></td>
			<td>
				<a class="btn btn-primary" href="<?php echo $this->url(
					array(
						'controller'	=>	'faturas',
						'action'		=>	'editar',
						'idFaturas'		=>	$lista->idFatura
					));?>">
						Editar
				</a>
				
				<a class="btn btn-warning" href="<?php echo $this->url(
					array(
						'controller'	=>	'faturas',
						'action'		=>	'delete',
						'idFaturas'		=>	$lista->idFatura
					));?>">
						Excluir
				</a>
			</td>
		</tr>
<?php }?>
		</tbody>
	</table>
</div>