<?php $this->headTitle('Relatório de Alunos Pendentes'); ?>
<div class="grid_16">

	<?php 
	header("Content-type:text/html; charset=utf-8");
	ob_start();	
	?>
	
	<table>
		<tr>
			<th><img src="/images/logosibb2.gif" height="120px" width="120px"></th>
			<th width="550px">
				<font size="5">SEMINÁRIO E INSTITUTO BATISTA BEREIANO</font>
				<p><font size="3">Rua Mar do Leste, 100, Pajuçara - CEP: 59.133-380 / Natal-RN</font></p>
				<font size="3">Email: <font color="blue">contato@seminariobereiano.com.br</font></font>
				<p><font size="3">Fone: (084) 3221-2520 / 3201-0083</font></p>
			</th>
		</tr>
	</table>
	
	<hr />
	
	<br />
	
	<h3 style="text-align: center">Relatório de Faturas Pendentes</h3>
	
	<br />
	
	<table border="1" cellpadding="5px" cellspacing="0" style="border-collapse: collapse; ">
		<thead>
			<tr style="padding: 3px;">
				<th style="text-align: left;"><h5><strong>Aluno</strong></h5></th>
				<th style="text-align: center;"><h5><strong>Mês/Ano</strong></h5></th>
				<th style="text-align: center;"><h5><strong>Valor da Fatura</strong></h5></th>
				<th style="text-align: center;"><h5><strong>Total à pagar</strong></h5></th>
				<th style="text-align: center;"><h5><strong>Status</strong></h5></th>
			</tr>
		</thead>
			<?php foreach ($this->rows as $fatura){

				$valor_total_pagamentos = 0;
				$total_restante = 0;
				$pagamentos_model = new Application_Model_DbTable_Pagamento();
				$pagamentos = $pagamentos_model->listar($fatura['idFatura']);
				foreach($pagamentos as $pagamento) :
									
						$pagamento->idPagamento;
						number_format($pagamento->valorPagamento,2,',','.'); $valor_total_pagamentos += $pagamento->valorPagamento; 
										
				endforeach;
									
				$valor = $fatura['valorFatura']; 
				$valor_pendente = number_format($valor - $valor_total_pagamentos,2); 
			?>
						
		<tbody>
			<?php if ( $valor_pendente != 0 ) : ?>
				<tr style="padding: 3px; ">
					<td style="text-align: left; width: 300px; font-size: 12px; "><?php echo $fatura['debitos'][0]['user']['Nome']; ?></td>
					<td style="width: 80px; text-align: center; font-size: 12px; "><?php echo $fatura['mes'] . '/' . $fatura['ano']; ?></td>
					<td style="width: 110px; text-align: center; font-size: 12px; ">R$ <?php echo number_format($valor,2,',','.'); ?></td>
					<td style="width: 110px; text-align: center; font-size: 12px; ">
				
						<?php if($valor_pendente == $fatura['valorFatura']){
							$total_apagar = $valor - ($valor * $fatura['desconto']/100); echo 'R$ ' . number_format($total_apagar,2,',','.');
							} else {
								echo 'R$ ' . number_format($valor_pendente,2,',','.');
							}
						?>
					</td>
					<td style="width: 100px; text-align: center; font-size: 12px;"><span class="label label-important">Pendente</span></td>
				</tr>			
			<?php endif; ?>
				
			<?php }?>
		</tbody>
		
	</table>
	
	<br /><br />
	
	<?php 
	 
	$html = ob_get_contents();
	ob_end_clean();
	
	define('MPDF_PATH', APPLICATION_PATH . '/../library/mpdf/');
	
	include(MPDF_PATH .'mpdf.php');
	
	$mpdf = new mPDF('pt', 'A4', 11);
	
	$mpdf->allow_charset_conversion = true;
	$mpdf->charset_in = 'utf-8';
	
	$mpdf->SetDisplayMode('fullpage');
	$mpdf->SetFooter('Relatório de Alunos com Faturas Pendentes {DATE j/m/Y} | {PAGENO}');
	$mpdf->WriteHTML($html);
	
	$arquivo = 'Recibo de Faturas Pendentes' . '.pdf';
	
	$mpdf->Output($arquivo, 'D');
	
	exit();
	
	?>
	
</div>