<?php $this->headTitle('Relatório de Alunos Pendentes'); ?>

<div class="grid_16">
	<div class="page-header">
		<h1>Relatório de Pendências -  
			<small>Lista de Alunos com faturas pendentes</small>
		</h1>
	</div>
	
	<br />
	
	<table class="table table-striped data-table" style="margin-bottom:0;">
		<thead style="color: #000; font-size: 16px; font-weight: 700; font-family: Georgia; ">
			<tr>
				<th style="text-align: center;">#</th>
				<th style="text-align: left;">Aluno</th>
				<th style="text-align: center;">Mês/Ano</th>
				<th style="text-align: center;">Valor da Fatura</th>
				<th style="text-align: center;">Valor Pendente</th>
				<th style="text-align: center;">Status</th>
			</tr>
		</thead>
		<tbody style="font-weight: 700; font-size: 12px;">
	
			<?php foreach ($this->rows as $fatura) {

				$valor_total_pagamentos = 0;
				$total_restante = 0;
				$pagamentos_model = new Application_Model_DbTable_Pagamento();
				$pagamentos = $pagamentos_model->listar($fatura['idFatura']);
				foreach($pagamentos as $pagamento) :
									
						$pagamento->idPagamento;
											
						number_format($pagamento->valorPagamento,2,',','.'); $valor_total_pagamentos += $pagamento->valorPagamento; 
										
				endforeach;
						
				$valor = $fatura['valorFatura']; 
				$valor_pendente = number_format($valor - $valor_total_pagamentos,2);  ?>

				<?php if ( $valor_pendente != 0 ) : ?>

				<tr>
					<td style="text-align: center; width: 5%;"><?php echo $fatura['idFatura']; ?></td>
					<td style="text-align: left; width: 30%;">

						<?php foreach($this->user as $user) :

							if($fatura['Usuario_idUsuario'] == $user['idUsuario']){

								echo $user['Nome'];

							}


						endforeach; ?>
							
					</td>
					<td style="width: 15%; text-align: center; "><?php echo $fatura['mes'] . '/' . $fatura['ano']; ?></td>
					<td style="width: 15%; text-align: center;">R$ <?php echo number_format($valor,2,',','.'); ?></td>
					<td style="width: 15%; text-align: center; ">
				
						<?php if($valor_pendente == $fatura['valorFatura']){
							$total_apagar = $valor - ($valor * $fatura['desconto']/100); echo 'R$ ' . number_format($total_apagar,2,',','.');
							} else {
								echo 'R$ ' . number_format($valor_pendente,2,',','.');
							}
						?>
					</td>
					<td style="width: 15%; text-align: center;">
						<span class="label label-important">Pendente</span>
					</td>	

					<?php endif; ?>		
				</tr>


			<?php } ?>

		</tbody>
	</table>

	<br /><br />
	
	<div style="text-align: right;">
		<br /><br /><br />
			<a style="font-size: 12px; height: 20px; " class="btn btn-inverse" href="<?php echo $this->url(
				array(
						'module'		=>	'admin',
						'controller'	=>	'faturas',
						'action'		=>	'relatorio-download'
				));?>">
							
				<strong>Baixar em .pdf</strong>
			</a>
		<br /><br /><br /><br />
	</div>
</div>