<?php $this->headTitle('Relatório de Alunos Pendentes'); ?>

<div class="grid_16">
	<div class="page-header">
		<h1 style="font-family: Georgia;">Relatório de Pendências -  
			<small>Lista de Alunos com faturas pendentes</small>
		</h1>
	</div>
	
	<br />
	
	<table class="table table-striped data-table-ajax data-table-row-details" data-endpoint="/admin/faturas/getRelatorio">
		<thead>
			<tr style="font-family: Liberation Serif; font-size: 16px; color: #000;">
				<th style="text-align: center;"><strong>#</strong></th>
				<th style="text-align: left;"><strong>Aluno</strong></th>
				<th style="text-align: center;"><strong>Mês/Ano</strong></th>
				<th style="text-align: center;"><strong>Valor da Fatura</strong></th>
				<th style="text-align: center;"><strong>Total à Pagar</strong></th>
				<th style="text-align: center;"><strong>Situação</strong></th>
			</tr>
		</thead>
		<tbody>
			

		</tbody>
	</table>
	
	<br /><br />
	
	<div style="text-align: right;">
		<br /><br /><br />
			<a style="font-size: 12px; height: 21px; width: 150px; " class="btn btn-inverse" href="<?php echo $this->url(
				array(
						'module'		=>	'admin',
						'controller'	=>	'faturas',
						'action'		=>	'relatorio-download'
				));?>">
							
				<strong>Baixar em .pdf</strong>
			</a>
		<br /><br /><br /><br /><br /><br /><br /><br />
	</div>
</div>