<?php $this->headTitle('Tela de Login')?>

<div class="grid_16">
	<div class="controls-group">
	 	<div class="controls">
	 		<?php echo $this->form; ?>
	 		
	 		<span class="errors"><?php echo $this->messages; ?></span>
	 		<span class="errors"><strong><?php echo $this->menssagem[0];  ?></strong></span>
		</div>
	</div>

<a href="<?php echo $this->url(
		
	array(
		'module'	=>	'default',
		'controller'=>	'index',
		'action'	=>	'recupera-senha'
	),null,1);?>"   class="btn btn-inverse dialog_button send_right" style="margin-top:-10px; margin-right: -5px">
		<img src="/images/icons/small/white/user.png">
	<span>Esqueceu sua senha?</span>
</a>



</div>