<?php $this->headTitle('Turmas'); ?>

<div class="grid_16">
	<div class="page-header">
		<h1>Lista de Turmas que Leciona
			<small>Veja todas as Turmas que leciona no semestre corrente</small>
		</h1>
	</div>
	<table class="table table-striped data-table" style="margin-bottom:0;">
		<thead>
			<tr>
				<th><h5>#</h5></th>
				<th><h5>Turmas</h5></th>
				<th><h5>Ano/Semestre</h5></th>
				<th><h5>Ações</h5></th>
			</tr>
		</thead>
		<tbody>
			<?php if($this->row != null){
				foreach($this->rows as $lista){?>
					<tr>
						<td><strong><?= $lista->idTurma;?></strong></td>
						<td><strong><?= $lista->Nome; ?></strong></td>
						<td><strong><?= $lista->Ano . '-' . $lista->Semestre; ?></strong></td>
						<td>
							<a class="btn btn-primary" href="<?= $this->url(
								array(
									'controller'	=>	'Nota',
									'action'		=>	'index',
									'idTurma'		=>	$lista->idTurma	
								));?>">
									Inserir Nota
							</a>
							
							<a class="btn btn-success" href="<?= $this->url(
								array(
									'controller'	=>	'presenca',
									'action'		=>	'index',
									'idTurma'		=>	$lista->idTurma
								));?>">
									Chamada
							</a>
							
							<a class="btn" href="<?= $this->url(
								array(
									'controller'	=>	'arquivo',
									'action'		=>	'index',
									'idTurma'		=>	$lista->idTurma
								));?>">
									Inserir Arquivo
							</a>
							
							<a class="btn btn-warning" href="<?= $this->url(
								array(
									'controller'	=>	'index',
									'action'		=>	'encerrar-turma',
									'idTurma'		=>	$lista->idTurma
								));?>">
									Encerrar Turma
							</a>
						</td>
					</tr>		
			<?php }
			}else{
				echo 'Usuário não leciona nenhuma turma até o momento.';		
			}?>			
		</tbody>
	</table>
</div>