<html>

<head>
	<title><?php $this->headTitle('Turmas'); ?></title>
</head>

<body>

<br />

<?php if($this->row != null){
	foreach($this->rows as $turma){ ?>
		Turma: <?php echo $turma->Nome . '/' . $turma->Ano . '-' . $turma->Semestre;?>
		&nbsp;
			<a href="<?php echo $this->url(
				array(
					'controller'	=>	'index',
					'action'		=>	'nota',
					'idTurma'		=>	$turma->idTurma
				));?>"><img title="Inserir Nota" src="/../images/ico_editar.gif" alt="Editar" width="20" height="20">&nbsp;&nbsp;
			</a>
			
			<a href="<?php echo $this->url(
				array(
					'controller'	=>	'index',
					'action'		=>	'presenca',
					'idTurma'		=>	$turma->idTurma
				));?>"><img title="Chamada" src="/../images/presenca.gif" alt="Presenca" width="20" height="20">&nbsp;&nbsp;
			</a>
			
			
			<a href="<?php echo $this->url(
				array(
					'controller'	=>	'index',
					'action'		=>	'upload',
					'idTurma'		=>	$turma->idTurma
				));?>"><img title="Inserir Arquivo" src="/../images/upload.jpg" alt="Ins. Arquivo" width="20" height="20">&nbsp;&nbsp;
			</a>
			
			
			<a href="<?php echo $this->url(
				array(
					'controller'	=>	'index',
					'action'		=>	'encerrar-turma',
					'idTurma'		=>	$turma->idTurma
				))?>"><img title="Encerrar Turma" src="/../images/check.gif" alt="Encerrar Turma" width="20" height="20"></img>
			</a>

<?php } //fim foreach
	} else{
		echo 'Usuário não leciona nenhuma turma até o momento.';
	}?>

<br />
<br />
	<form action="/professor/index/nota" method="post">
		<input type="submit" name="back" value="Voltar"></input>
	</form>

<br /><br />

</body>
</html>
