<?php $this->headTitle('Detalhes do Cadastro'); ?>

<div class="grad_16">
	<div class="page-header">
		<h1>Dados cadastrais do Curso
			<small>Veja todos os detalhes</small>
		</h1>
	</div>
	<br />
		<div class="container">
			<h4>Nome do Curso: <span style="color:#069;"><?= $this->row['Nome']; ?></span></h4><br/>
			<h4>Duração do Curso: <span style="color:#069;"><?= $this->row['Duracao']; ?></span></h4><br/>
			<h4>Descrição do Curso: <span style="color:#069;"><?= $this->row['Descricao']; ?></span></h4><br/>
		</div>
	
	<br /><br />

	
	
		

	
</div>