<?php $this->headTitle('Listagem de Cursos'); ?>

<div class="grid_16">
  	<div class="page-header">
	    <h1>Cursos Cadastrados
		    <small>Veja toda a lista de cursos cadastrados</small>
	    </h1>
  	</div>
  	
  	<table class="table table-striped data-table" style="margin-bottom:0;">
	    <thead>
	      <tr>
	        <th><h5>#</h5></th>
	        <th><h5>Curso</h5></th>
	        <th><h5>Duração</h5></th>
	        <th><h5>Ações</h5></th>
	      </tr>
	    </thead>
	    <tbody>
<?php foreach ($this->rows as $lista) { ?>
	<tr>
		<td><strong><?= $lista->idCurso; ?></strong></td>
		<td><strong><?= $lista->Nome; ?></strong></td>
		<td><strong><?= $lista->Duracao; ?></strong></td>
		<td>
			<a href="<?= $this->url(
				array(
					'controller'	=>	'curso',
					'action'		=>	'detalhes',
					'idCurso'		=>	$lista->idCurso	
				))?>">
					<img src="/images/icons/small/grey/lupa.png" title="Detallhes"/>
			</a>
		
		
		
			<a class="btn btn-primary" href="<?php echo $this->url(
				array(
					'controller'=>'curso',
					'action'	=>'editar',
					'idCurso'	=>$lista->idCurso
				));?>">
					Editar
			</a>
			
			<a class="btn btn-warning" href="<?php echo $this->url(
				array(
					'controller'=>'curso',
					'action'	=>'delete',
					'idCurso'	=>$lista->idCurso
				));?>">
					Excluir
			</a>		
		</td>
	</tr>
	
<?php }?> <!-- fim foreach -->
</table>
</div>