<?php $this->headTitle('Lista')?>

<div class="grid_16">
	<div class="page-header">
		<h2>Lista de arquivos da disciplina de <?php echo $this->turma; ?></h2>
	</div>
	
	<table class="table table-striped data-table">
		<thead>
			<tr>
				<th><font size="2" color="black"><strong>#</strong></font></th>
				<th><font size="2" color="black"><strong>Nome</strong></font></th>
				<th style=" text-align: center;"><font size="2" color="black"><strong>Ano/Semestre</strong></font></th>
				<th style=" text-align: center;"><font size="2" color="black"><strong>Data</strong></font></th>
				<th style=" text-align: center;"><font size="2" color="black"><strong>Compartilhado</strong></font></th>
				<th style=" text-align: center;"><font size="2" color="black"><strong>Ações</strong></font></th>
			</tr>
		</thead>
		
		<tbody>
			<?php foreach($this->rows as $lista){?>
			<tr style="background: #EEE;">
				<td style="width: 40px;"><strong><?php echo $lista->idArquivos; ?></strong></td>
				<td><strong><?php echo $lista->Nome; ?></strong></td>
				<td style="width: 150px; text-align: center;"><strong><?php echo $lista->Ano . '/' . $lista->Semestre; ?></strong></td>
				<td style="width: 150px; text-align: center;"><strong><?php echo $lista->Data; ?></strong></td>
				<td style="width: 100px; text-align: center;"><strong>
				
				<?php switch ($lista->Status){
					case 'ativo':
						echo "<span class='label label-inverse'>Sim</span>";
						break;
					case 'inativo':
						echo "<span class='label label-important'>Não</span>";
						break;
				}?>
				
				</strong></td>
				<td style="text-align: center; width: 350px;">
					<a style="width: 55px; font-size: 11px;" class="btn btn-primary" href="<?php echo $this->url(
						array(
							'controller'	=>	'arquivo',
							'action'		=>	'editar',
							'idArquivo'		=>	$lista->idArquivos
						));?>">
							<strong>Editar</strong>
					</a>
					
					<a style="width: 80px; font-size: 11px;" class="btn btn-success" href="<?php echo $this->url(
						array(
							'controller'	=>	'arquivo',
							'action'		=>	'download',
							'idArquivo'		=>	$lista->idArquivos
						));?>">
							<strong>Baixar Arquivo</strong>
					</a>
					
					<a style="width: 55px; font-size: 11px;" class="btn btn-danger" href="<?php echo $this->url(
						array(
							'controller'	=>	'arquivo',
							'action'		=>	'delete',
							'idArquivo'		=>	$lista->idArquivos
						));?>">
							<strong>Excluir</strong>
					</a>
				</td>
			</tr>
			<?php }?>
		</tbody>
	</table>
	
	<br />
</div>