<?php $this->headTitle('Listagme de Disciplinas'); ?>

<div class="grid_16">
  	<div class="page-header">
	    <h1>Disciplinas Cadastradas
		    <small>Veja toda a lista das disciplinas cadastradas</small>
	    </h1>
  	</div>
  	<table class="table table-striped data-table" style="margin-bottom:0;">
	    <thead>
	      <tr>
	        <th><h5>#</h5></th>
	        <th><h5>Disciplina</h5></th>
	        <th><h5>Qtd. Créditos</h5></th>
	        <th><h5>Ações</h5></th>
	      </tr>
	    </thead>
	    <tbody>
<?php foreach ($this->rows as $lista) { ?>
	<tr>
		<td><strong><?= $lista->idDisciplina; ?></strong></td>
		<td><strong><?= $lista->Disciplina; ?></strong></td>
		<td><strong><?= $lista->QntdCred; ?></strong></td>
		<td>
			<a class="btn btn-primary" href="<?= $this->url(
				array(
					'controller'=>'disciplina',
					'action'	=>'editar',
					'idDisciplina'	=>$lista->idDisciplina
				));?>">
					Editar
			</a>
			
			<a class="btn btn-warning" href="<?= $this->url(
				array(
					'controller'=>'disciplina',
					'action'	=>'delete',
					'idDisciplina'	=>$lista->idDisciplina
				));?>">
					Excluir
			</a>		
		</td>
	</tr>
	
<?php }?> <!-- fim foreach -->
</table>

	<br />
</div>