<?php $this->headTitle('Listagme de Disciplinas'); ?>

<div class="grid_16">
  	<div class="page-header">
	    <h1>Disciplinas Cadastradas
		    <small>Veja toda a lista das disciplinas cadastradas<small>
	    </h1>
  	</div>
  	<table class="table table-striped data-table" style="margin-bottom:0;">
	    <thead>
	      <tr>
	        <th>#</th>
	        <th>Disciplina</th>
	        <th>Qtd. Créditos</th>
	        <th>Ações</th>
	      </tr>
	    </thead>
	    <tbody>
<?php foreach ($this->rows as $lista) { ?>
	<tr>
		<td><?php echo $lista->idDisciplina; ?></td>
		<td><?php echo $lista->Disciplina; ?></td>
		<td><?php echo $lista->QntdCred; ?></td>
		<td id="action_res">
			<a class="btn btn-primary" href="<?php echo $this->url(
				array(
					'controller'=>'disciplina',
					'action'	=>'editar',
					'idDisciplina'	=>$lista->idDisciplina
				));?>">
					Editar
			</a>
			
			<a class="btn btn-warning" href="<?php echo $this->url(
				array(
					'controller'=>'disciplina',
					'action'	=>'delete',
					'idDisciplina'	=>$lista->idDisciplina
				));?>">
					Excluir
			</a>		
		</td>
	</tr>
	
<?php }?> <!-- fim foreach -->
</table>
</div>