<?php $this->headTitle('Inserir Notas'); ?>

<div class="grid_16">

	<?php if(empty ($this->find['Turma_idTurma'])){ ?>
		<br /><br />
		<div style="color: red; font-size: 20px;">
			<strong>Ainda não há alunos matriculados nessa Turma.</strong>
		</div>
		
		<br /><br /><br /><br />
	<?php } else { 	?>
		
	<div class="page-header">
		<?php foreach ($this->linha as $disc){?>
			<h2>Insira notas aos alunos da Turma de <?php echo $disc->Nome;?></h2>
		<?php }?>
	</div>
 
 	<br /><br />
 
 	<div class="container">
 	
 		<table class="table-striped" cellpadding="5px" cellspacing="2" style="border-collapse: collapse;">
 		
 			<thead>
 			
 				<tr style="height: 25px; background: #1C94C4;">
 				
					<th style="width: 600px; padding-top: 5px;"><font size="3" color="white">ALUNOS</font></th>
					<th style="width: 250px;"><font size="3" color="white">UNIDADE 1</font></th>
					<th style="width: 250px;"><font size="3" color="white">UNIDADE 2</font></th>
					<th style="width: 250px;"><font size="3" color="white">UNIDADE 3</font></th>
					<th style="width: 250px;"><font size="3" color="white">MÉDIA FINAL</font></th>
					
				</tr>
				
 			</thead> 
 			
 			<tbody>
 			
 				<form action="/admin/professor/post-nota" method="post" id="form-prof">
 				
 					<fieldset>
 					
 						<?php 
 							$i = 0;
 							foreach($this->rows as $users) : 
 							
 								$nota = new Application_Model_DbTable_Nota();
 								$id = $users->idUsuario_has_Turma;
 								$media = $nota->media($id);
 							
 								$idNota = ( $this->nota && isset($this->nota[$i]) ) ? $this->nota[$i]['idNota'] : '';
 								$unit1  = ( $this->nota && isset($this->nota[$i]) && ! is_null($this->nota[$i]['Unit1']) ) ? $this->nota[$i]['Unit1']  : ' ';
 								$unit2  = ( $this->nota && isset($this->nota[$i]) && ! is_null($this->nota[$i]['Unit2']) ) ? $this->nota[$i]['Unit2']  : ' ';
 								$unit3  = ( $this->nota && isset($this->nota[$i]) && ! is_null($this->nota[$i]['Unit3']) ) ? $this->nota[$i]['Unit3']  : ' ';

							if($users->Status != 'inativo') : ?>
							<tr style="background: #EEE ">
								<input type="hidden" name="idMatricula[]" value="<?php echo $users->idUsuario_has_Turma; ?>"/>
								<input type="hidden" name="idTurma[]" value="<?php echo $users->Turma_idTurma; ?>"/>
								<input type="hidden" name="idNota[]" value="<?php echo $idNota ?>"/>
								
								<td style="text-align: left; padding-left: 10px; ">
									<strong>
										<font size="3" color="black"><a data-toggle="modal" href="#myModal-<?php echo $users->findParentRow('Application_Model_DbTable_Usuario')->idUsuario; ?>">
											<?php echo $users->findParentRow('Application_Model_DbTable_Usuario')->Nome; ?></a>
										</font>
									</strong>
									<div id="myModal-<?php echo $users->findParentRow('Application_Model_DbTable_Usuario')->idUsuario; ?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
										<div class="modal-header">
				    						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				    						<h3 id="myModalLabel">Dados Cadastrais do Usuário</h3>
				  						</div>
			  							<div class="modal-body">
			    						<div style="margin: 0 0px 0 30px; width: 100px;"><img src="/files/<?php echo $users->findParentRow('Application_Model_DbTable_Usuario')->Foto; ?>" width="100" height="120"></img></div>
			    						<div style="margin: -120px 0px 0 140px; text-align: left;">

				    						<p><strong><font size="2">Nome do Usuário: <span style="color:#069;"><?php echo $users->findParentRow('Application_Model_DbTable_Usuario')->Nome; ?></span></font></strong></p>
				    						<p><strong><font size="2">Endereço: <span style="color:#069;"><?php echo $users->findParentRow('Application_Model_DbTable_Usuario')->Endereco; ?></span></font></strong></p>
				    						<p><strong><font size="2">CEP: <span style="color:#069;"><?php echo $users->findParentRow('Application_Model_DbTable_Usuario')->CEP; ?></span></font></strong></p>
				    						<p><strong><font size="2">Telefone(s): <span style="color:#069;"><?php echo $users->findParentRow('Application_Model_DbTable_Usuario')->Telefone . ' / ' . $users->findParentRow('Application_Model_DbTable_Usuario')->Celular; ?></span></font></strong></p>
				    						<p><strong><font size="2">Data de Nascimento: <span style="color:#069;"><?php echo $users->findParentRow('Application_Model_DbTable_Usuario')->DataNascimento; ?></span></font></strong></p>
				    						<p><strong><font size="2">CPF: <span style="color:#069;"><?php echo $users->findParentRow('Application_Model_DbTable_Usuario')->CPF; ?></span></font></strong></p>
				    						<p><strong><font size="2">Nome da Mãe: <span style="color:#069;"><?php echo $users->findParentRow('Application_Model_DbTable_Usuario')->NomeMae; ?></span></font></strong></p>
				    						<p><strong><font size="2">Nome do Pai: <span style="color:#069;"><?php echo $users->findParentRow('Application_Model_DbTable_Usuario')->NomePai; ?></span></font></strong></p>
				    						<p><strong><font size="2">E-mail: <span style="color:#069;"><?php echo $users->findParentRow('Application_Model_DbTable_Usuario')->Email; ?></span></font></strong></p>
				    						<p><strong><font size="2">Igreja: <span style="color:#069;"><?php echo $users->findParentRow('Application_Model_DbTable_Usuario')->findParentRow('Application_Model_DbTable_Igreja')->Igreja; ?></span></font></strong></p>
				    						<p><strong><font size="2">Curso: <span style="color:#069;"><?php echo $users->findParentRow('Application_Model_DbTable_Usuario')->findParentRow('Application_Model_DbTable_Curso')->Nome; ?></span></font></strong></p>
				    						<p><strong><font size="2">Tipo: <span style="color:#069;"><?php switch ($users->findParentRow('Application_Model_DbTable_Usuario')->Tipo) {
													case 1:
														echo "Administrador";
														break;
													case 2:
														echo "Professor";
														break;
													case 3:
														echo "Aluno";
														break;
													} ?></span></font></strong></p>
				    					
			    						</div>
			  							</div>
			  							<div class="modal-footer">
			    							<button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
										</div>
									</div>
								</td>
								<td style="text-align: center; padding-top: 7px; ">
									<input style="text-align: center" type="text" class="input-small" name="unit1[]" class="nota" value="<?php if($unit1 == 0){echo ' ';} else { echo number_format($unit1,2,',','.'); } ?>"/>
								</td>
								
								<td style="text-align: center;" >
									<input style="text-align: center" type="text" class="input-small" name="unit2[]" class="nota" value="<?php if($unit2 == null){echo ' ';} else { echo number_format($unit2,2,',','.'); } ?>"/>
								</td>
								
								<td style="text-align: center;" >
									<input style="text-align: center" type="text" class="input-small" name="unit3[]" class="nota" value="<?php if($unit3 == 0){echo ' ';}else { echo number_format($unit3,2,',','.'); } ?>"/>
								</td>
								
								<?php if($media < 7){ ?>
									<td style="text-align: center; color:red; "><strong><?php echo number_format($media, 2,',','.'); ?></strong></td>
								<?php } else { ?>
									<td style="text-align: center; "><strong><?php echo number_format($media, 2,',','.'); ?></strong></td>
								<?php } ?>
								
	    					</tr>
	    					
	    					<?php endif; ?>	
						<?php $i++; endforeach; ?>
							<tr valing="baseline">
								<td><input id="btn-prof" class="btn btn-primary" type="submit" name="submit" value="Salvar"/></td>
							</tr>
 					</fieldset>
 				</form>
 			</tbody>	

 		</table>
 	</div>
 	
	<br /><br /><br />
	
	<?php } ?>
	
</div>