<?php $this->headTitle('Inserir Notas'); ?>

<div class="grid_16">
	
	<?php if(empty ($this->find['Turma_idTurma'])){ ?>
		<br /><br />
		<div style="color: red; font-size: 20px;">
			<strong>Ainda não há alunos matriculados nessa Turma.</strong>
		</div>
		
		<br /><br /><br /><br />
	<?php } else { 	?>
	
	
	<div class="page-header">
		<?php foreach ($this->linha as $disc){?>
			<h2>Insira notas aos alunos da Turma de <?php echo $disc->Nome;?></h2>
		<?php }?>
	</div>
 
 	<br /><br />
 
 	<div class="container">
 	
 		<table class="table-striped" cellpadding="5px" cellspacing="2" style="border-collapse: collapse;">
 		
 			<thead>
 			
 				<tr style="height: 25px; background: #1C94C4;">
 				
					<th style="width: 600px; padding-top: 5px;"><font size="3" color="white">ALUNOS</font></th>
					<th style="width: 250px;"><font size="3" color="white">UNIDADE 1</font></th>
					<th style="width: 250px;"><font size="3" color="white">UNIDADE 2</font></th>
					<th style="width: 250px;"><font size="3" color="white">UNIDADE 3</font></th>
					<th style="width: 250px;"><font size="3" color="white">MÉDIA FINAL</font></th>
					
				</tr>
				
 			</thead> 
 			
 			<tbody>
 			
 				<form action="/professor/nota/post-nota" method="post" id="form-prof">
 				
 					<fieldset>
 						<?php 
 							$i = 0;
 							foreach($this->rows as $users) :
 							
 							$nota = new Application_Model_DbTable_Nota();
 							$id = $users->idUsuario_has_Turma;
 							$media = $nota->media($id);

 								$idNota = ( $this->nota && isset($this->nota[$i]) ) ? $this->nota[$i]['idNota'] : '';
 								$unit1  = ( $this->nota && isset($this->nota[$i]) && ! is_null($this->nota[$i]['Unit1']) ) ? $this->nota[$i]['Unit1']  : ' ' ;
 								$unit2  = ( $this->nota && isset($this->nota[$i]) && ! is_null($this->nota[$i]['Unit2']) ) ? $this->nota[$i]['Unit2']  : ' ' ;
 								$unit3  = ( $this->nota && isset($this->nota[$i]) && ! is_null($this->nota[$i]['Unit3']) ) ? $this->nota[$i]['Unit3']  : ' ' ;

 							//var_dump($this->nota->toArray());
							if($users->Status != 'inativo') : ?>
							<tr style="background: #EEE ">
								<input type="hidden" name="idMatricula[]" value="<?php echo $users->idUsuario_has_Turma; ?>"/>
								<input type="hidden" name="idTurma[]" value="<?php echo $users->Turma_idTurma; ?>"/>
								<input type="hidden" name="idNota[]" value="<?php echo $idNota ?>"/>

								<td style="text-align: left; padding-left: 10px; ">
									<strong>
										<font size="3" color="black">
											<?php echo $users->findParentRow('Application_Model_DbTable_Usuario')->Nome; ?>
										</font>
									</strong>
								</td>
								
								<td style="text-align: center; padding-top: 7px; ">
									<input style="text-align: center" type="text" class="input-small" name="unit1[]" class="nota" value="<?php if ( $unit1 == 0 ){echo ' ' ; } else{ echo number_format($unit1,2,',','.'); }  ?>"/>
								</td>
								
								<td style="text-align: center;" >
									<input style="text-align: center" type="text" class="input-small" name="unit2[]" class="nota" value="<?php if ( $unit2 == 0 ){echo ' ' ; } else{ echo number_format($unit2,2,',','.'); }  ?>"/>
								</td>
								
								<td style="text-align: center;" >
									<input style="text-align: center" type="text" class="input-small" name="unit3[]" class="nota" value="<?php if ( $unit3 == 0 ){echo ' ' ; } else{ echo number_format($unit3,2,',','.'); }  ?>"/>
								</td>
								
								<?php if($media < 7){ ?>
									<td style="text-align: center; color:red; "><strong><?php echo number_format($media, 2,',','.'); ?></strong></td>
								<?php } else { ?>
									<td style="text-align: center; "><strong><?php echo number_format($media, 2,',','.'); ?></strong></td>
								<?php } ?>
	    					</tr>
	    					
	    					<?php endif; ?>	
						<?php $i++; endforeach; ?>
							<tr valing="baseline">
								<td><input id="btn-prof" class="btn btn-primary" type="submit" name="submit" value="Salvar"/></td>
							</tr>
 					</fieldset>
 				</form>
 			</tbody>	

 		</table>
 	</div>
 	
	<br /><br /><br />
	
	<?php } ?>
	
</div>