<?php $this->headTitle('Lista')?>
	
<div class="grid_16">
	<div class="page-header">
		<h2> 
			<? foreach ($this->linha as $disc){?>
				Lista de alunos com notas na turma de <?= $disc->Nome; ?>
			<? }?>
		</h2>
	</div>
	
	<br />
	
	<table class="table table-striped data-table" style="margin-bottom:0;">
		<thead>
			<tr>
				<th><h5>#</h5></th>
				<th><h5>Nome</h5></th>
				<th><h5>Unidade 1</h5></th>
				<th><h5>Unidade 2</h5></th>
				<th><h5>Unidade 3</h5></th>
				<th><h5>Ação</h5></th>
			</tr>
		</thead>
		<tbody>
			<? $model = new Application_Model_DbTable_Matricula();?>
			<?foreach($this->result as $lista){?>
				<tr>
					<td><strong><?= $lista->idNota; ?></strong></td>
					<?php $idUser = $lista->idUsuario_has_Turma;
						  $query = $model->getId($idUser); ?>
					<td><strong><?= $query->findParentRow('Application_Model_DbTable_Usuario')->Nome; ?></strong></td>
					<td><strong><? if($lista->Unit1 == 0){echo '-';}else{echo $lista->Unit1;} ?></strong></td>
					<td><strong><? if($lista->Unit2 == 0){echo '-';}else{echo $lista->Unit2;} ?></strong></td>
					<td><strong><? if($lista->Unit3 == 0){echo '-';}else{echo $lista->Unit3;} ?></strong></td>
					<td>
						<a class="btn btn-warning" href="<?= $this->url(
							array(
								'controller'	=>	'nota',
								'action'		=>	'delete',
								'idNota'		=>	$lista->idNota
							));?>">
								Excluir
						</a>
					</td>
				</tr>
		<? }?>
		</tbody>
	</table>
	
	<br />
	
</div>