<div id="menu">
	<ul>
		<li class="titulo">Cadastro</li>
			<!-- <ul>
				<li class="subtitulo">Aluno</li>
				<li class="subtitulo">Professor</li>
				<li class="subtitulo">Igreja</li>
				<li class="subtitulo">Disciplina</li>
			</ul> -->
		<li class="titulo">Matrícula</li>
			<!--<ul>
				<li class="subtitulo">Aluno</li>
				<li class="subtitulo">Professor</li>
				<li class="subtitulo">Igreja</li>
				<li class="subtitulo">Disciplina</li>
			</ul>-->
		<li class="titulo">Financeiro</li>
			<!--<ul>
				<li class="subtitulo">Aluno</li>
				<li class="subtitulo">Professor</li>
				<li class="subtitulo">Igreja</li>
				<li class="subtitulo">Disciplina</li>
			</ul>-->
	</ul>
</div>