<?php echo $this->partial('_header.phtml', 'admin'); ?>
	<div id="pjax">
		<div id="wrapper">
			<div class="isolate">
				<div class="center narrow" >
					<img class="center" style="width: 200px; " src="/images/logosibb2.gif" />
					<div class="main_container full_size container_16 clearfix">
						<div class="box">
							<div class="block">
							<?php echo $this->messages;  ?>
							<form class="form-horizontal" style="margin: 0px 0 0; padding-top:20px;" action="" method="post">
					        <fieldset>
					          <div class="control-group">
					            <label class="control-label" for="input01">Email</label>
					            <div class="controls">
					              <input type="text" class="input-large" name="login" id="input01">
					            </div>
					          </div>
					          <div class="control-group">
					            <label class="control-label" for="input01">Password</label>
					            <div class="controls">
					              <input type="password" name="senha" class="input-large" id="input01">
					            </div>
					          </div>

					          <div class="control-group">
					          	<div class="controls">
					            	<button type="submit" class="btn">Login</button>
					          	</div>
					          </div>
					        </fieldset>
				        </form>
							</div>
						</div>
					</div>
					<button data-dialog="dialog_register" class="btn btn-inverse dialog_button send_right" style="margin-top:10px;">
						<img src="images/icons/small/white/user.png">
						<span>Não registrado ?</span>
					</button>
				</div>
			</div>
		<?php echo $this->partial('dialogs/dialog_welcome.php', 'admin'); ?>
<?php echo $this->partial("_footer.phtml", 'admin'); ?>