<style>body {background: url("../images/tela_inicia.png") }
</style>
<?php echo $this->partial('_header.phtml', 'admin'); ?>
	<div id="pjax">
		
		<div id="wrapper">
			<div class="isolate">
				<div class="center narrow" >
					<div class="main_container full_size container_16 clearfix">
						<div class="box">
							<div class="block">
							
							<!--<form class="form-horizontal" style="margin: 0px 0 0; padding-top:20px;" action="" method="post">
					        <fieldset>
					          <div class="control-group">
					            <label class="control-label" for="input01">Email</label>
					            <div class="controls">
					              <input type="text" class="input-large" name="login" id="input01">
					            </div>
					          </div>
					          <div class="control-group">
					            <label class="control-label" for="input01">Password</label>
					            <div class="controls">
					              <input type="password" name="senha" class="input-large" id="input01">
					            </div>
					          </div>
								<?php echo $this->messages;  ?>
					          <div class="control-group">
					          	<div class="controls">
					            	<button type="submit" class="btn">Login</button>
					          	</div>
					          </div>
					        </fieldset>
				        </form> -->
				        <?php echo $this->layout()->content; ?>
				        
							</div>
						</div>
					</div>
					<a href="<?php echo $this->url(
							array(
								'module'	=>	'default',
								'controller'=>	'index',
								'action'	=>	'recupera-senha'
							),null,1);?>" data-dialog="dialog_register" class="btn btn-inverse dialog_button send_right" style="margin-top:10px;">
						<img src="images/icons/small/white/user.png">
						<span>Esqueceu sua senha?</span>
					</a>
				</div>
			</div>
		</div>
	</div>		
		<?php echo $this->partial('dialogs/dialog_welcome.php', 'admin'); ?>
<?php echo $this->partial("_footer.phtml", 'admin'); ?>