<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headLink(); ?>
</head>
<body>
		<div id="tudo">
			<?php //echo $this->partial("_header.phtml"); ?>
			<?php //echo $this->partial("_menu.phtml"); ?>
					<div id="conteudo">
						<?php echo $this->layout()->content; ?>
					</div>
			<?php //echo $this->partial("_footer.phtml"); ?>
		</div>
	</body>
</html>
