<?php $this->headTitle('Listagem de Débitos'); ?>

<div class="grid_16">
	<div class="page-header">
		<h1>Débitos Cadastrados
			<small>Veja toda lista dos débitos cadastrados</small>
		</h1>
	</div>
	
	<table class="table table-striped data-table" style="margin-bottom:0;">
		<thead>
			<tr>
				<th><h5>#</h5></th>
				<th><h5>Mês Pagamento</h5></th>
				<th><h5>Ano Pagamento</h5></th>
				<th><h5>Desconto</h5></th>
				<th><h5>Ações</h5></th>
			</tr>
		</thead>
		<tbody>
	<?php foreach($this->rows as $lista){?>
		<tr>
			<td><strong><?= $lista->idDebitos;?></strong></td>
			<td><strong><?= $lista->mesPagamento;?></strong></td>
			<td><strong><?= $lista->anoPagamento;?></strong></td>
			<td><strong><?= $lista->descontoMes;?></strong></td>
			<td>
				<a class="btn btn-primary" href="<?= $this->url(
					array(
						'controller'	=>	'debitos',
						'action'		=>	'editar',
						'idDebitos'		=>	$lista->idDebitos
					))?>">
						Editar
				</a>
				
				<a class="btn btn-warning" href="<?= $this->url(
					array(
						'controller'	=>	'debitos',
						'action'		=>	'delete',
						'idDebitos'		=>	$lista->idDebitos
					))?>">
						Excluir
				</a>
			</td>
		</tr>
	<?php }?>
		</tbody>
	</table>
	
	<br />
</div>