<?php $this->headTitle('Listagem de Débitos'); ?>

<div class="grid_16">
	<div class="page-header">
		<h1>Débitos Cadastrados
			<small>Veja toda lista dos débitos cadastrados</small>
		</h1>
	</div>
	
	<table class="table table-striped data-table" style="margin-bottom:0;">
		<thead>
			<tr>
				<th>#</th>
				<th>Mês Pagamento</th>
				<th>Ano Pagamento</th>
				<th>Desconto</th>
				<th>Ações</th>
			</tr>
		</thead>
		<tbody>
	<?php foreach($this->rows as $lista){?>
		<tr>
			<td><?php echo $lista->idDebitos;?></td>
			<td><?php echo $lista->mesPagamento;?></td>
			<td><?php echo $lista->anoPagamento;?></td>
			<td><?php echo $lista->descontoMes;?></td>
			<td>
				<a class="btn btn-primary" href="<?php echo $this->url(
					array(
						'controller'	=>	'debitos',
						'action'		=>	'editar',
						'idDebitos'		=>	$lista->idDebitos
					))?>">
						Editar
				</a>
				
				<a class="btn btn-warning" href="<?php echo $this->url(
					array(
						'controller'	=>	'debitos',
						'action'		=>	'delete',
						'idDebitos'		=>	$lista->idDebitos
					))?>">
						Excluir
				</a>
			</td>
		</tr>
	<?php }?>
		</tbody>
	</table>
</div>