<?php $this->headTitle('Listagem de Débitos'); ?>

<div class="grid_16">
	<div class="page-header">
		<h1>Débitos Cadastrados
			<small>Veja toda lista dos débitos cadastrados</small>
		</h1>
	</div>

	<div class="row">
		<div class="span12">

			<form action="/admin/debitos" method="GET" class="row">
				<fieldset class="span12">

					<legend>Escolha o Aluno</legend>
					<select class="sibb-select2 " id="aluno" style="width:200px" name="aluno">
						<option value="-1">Todos</option>
						<?php
						$users = new Application_Model_DbTable_Usuario();
						$users = $users->fetchAll();
						foreach ($users as $user) :
							?>
							<option <?php if ( $user->idUsuario == $this->user_id) echo 'selected' ?> value="<?= $user->idUsuario; ?>"><?= $user->Nome; ?></option>
						<?php endforeach; ?>
					</select>


					<input type="submit" value="Filtrar" class="btn btn-danger span2" />

				</fieldset>


			</form>
		</div>
	</div>

	<form action="/admin/faturas/novo" method="POST">
		<table class="table table-striped data-table" style="margin-bottom:0;">
			<thead>
				<tr>
					<th><font size="3" color="black"><strong>Marcar</strong></font></th>
					<th><font size="3" color="black"><strong>#</strong></font></th>
					<th ><font size="3" color="black"><strong>Aluno</strong></font></th>
					<th ><font size="3" color="black"><strong>Descrição</strong></font></th>
					<th ><font size="3" color="black"><strong>Mes/Ano</strong></font></th>
					<th ><font size="3" color="black"><strong>Valor</strong></font></th>
					<th ><font size="3" color="black"><strong>Ações</strong></font></th>
				</tr>
			</thead>
			<tbody>
		<?php
			$valor_total = 0;
			foreach($this->rows as $debito){?>
				<?php $user_id = $debito['user']['idUsuario']; ?>
			<tr style="background: #EEE;">
				<td width="100px"> <input type="checkbox" name="debitos[]" value="<?php echo $debito['idDebitos']; ?>" class="single-debito" /></td>
				<td width="50px" ><strong><?php echo $debito['idDebitos']; ?></strong></td>
				<td width="200px""><?php echo $debito['user']['Nome']; ?></td>
				<td >
					<?php
						$desc_debito = '';
						if ( $debito['type'] == 'servico' ) {
							$desc_debito = "Serviço: " . $debito['servico']['nome_servico'] . ' - ' . $debito['servico']['descricao_servico'];
						} else if ( $debito['type'] == 'matricula' ) {
							$desc_debito = 'Matrícula: ' . $debito['matricula']['nome_turma'] .
								" ({$debito['matricula']['disciplina']}) {$debito['matricula']['ano_turma']}.{$debito['matricula']['semestre_turma']}";
						}
						echo $desc_debito;
					?>
				</td>


				<td width="50px"><strong><?php echo $debito['mesPagamento'] .'/' . $debito['anoPagamento'];?></strong></td>
				<td width="100px">
					<strong>
						R$
						<?php
							$valor = $debito[$debito['type']]['valor_final'];
							echo number_format($valor,2) . " (" . $debito['descontoMes'] . "%)";
							$valor_total += $valor;
						?>
					</strong></td>
				<td width="50px">
					<a id="btn-admin" class="btn btn-primary" href="<?php echo $this->url(
						array(
							'controller'	=>	'debitos',
							'action'		=>	'editar',
							'idDebitos'		=>	$debito['idDebitos']
						))?>">
							Editar
					</a>

					<!--<a id="btn-admin" class="btn btn-danger" href="<?php echo $this->url(
						array(
							'controller'	=>	'debitos',
							'action'		=>	'delete',
							'idDebitos'		=>	$debito['idDebitos']
						))?>">
							Excluir
					</a>-->
				</td>
			</tr>
		<?php }?>
			</tbody>
			<tfoot>
				<tr style="background: #EEE;">
					<td><input type="checkbox" class="select-all" data-select=".single-debito"  /> Selecionar Tudo</td>
					<td></td>
					<td></td>
					<td></td>
					<td><font size="4" color="black"><strong>Total</strong></font></td>
					<td><font size="4" color="black"><strong>R$ <?php echo number_format($valor_total, 2); ?></strong></font></td>
					<td></td>
				</tr>
				<tr>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td><input type="submit" disabled value="Gerar Fatura" data-enabled=".single-debito" class="btn btn-success dependent-btn"/></td>
				</tr>

			</tfoot>

		</table>
		<input type="hidden" name="user_id" value="<?php echo $user_id; ?>"/>
	</form>


	
	<br /><br />
</div>
