<?php $this->headTitle('Lista')?>

<div class="grid_16">
	<div class="page-header">
		<h2>Lista de arquivos da disciplina de <?= $this->turma; ?></h2>
	</div>
	
	<table class="table table-striped data-table" style="margin-bottom:0;">
		<thead>
			<tr>
				<th><h5>#</h5></th>
				<th><h5>Nome</h5></th>
				<th><h5>Ano/Semestre</h5></th>
				<th><h5>Data</h5></th>
				<th><h5>Compartilhado</h5></th>
				<th><h5>Ações</h5></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($this->rows as $lista){?>
			<tr>
				<td><strong><?= $lista->idArquivos; ?></strong></td>
				<td><strong><?= $lista->Nome; ?></strong></td>
				<td><strong><?= $lista->Ano . '/' . $lista->Semestre; ?></strong></td>
				<td><strong><?= $lista->Data; ?></strong></td>
				<td><strong><?= $lista->Status; ?></strong></td>
				<td>
					<a class="btn btn-primary" href="<?= $this->url(
						array(
							'controller'	=>	'arquivo',
							'action'		=>	'editar',
							'idArquivo'		=>	$lista->idArquivos
						));?>">
							Editar
					</a>
					
					<a class="btn btn-success" href="<?= $this->url(
						array(
							'controller'	=>	'arquivo',
							'action'		=>	'download',
							'idArquivo'		=>	$lista->idArquivos
						));?>">
							Download
					</a>
					
					<a class="btn btn-warning" href="<?= $this->url(
						array(
							'controller'	=>	'arquivo',
							'action'		=>	'delete',
							'idArquivo'		=>	$lista->idArquivos
						));?>">
							Excluir
					</a>
				</td>
			</tr>
			<?php }?>
		</tbody>
	</table>
	
	<br />
</div>