<?php $this->headTitle('Matérial de Aulas'); ?>

<div class="grid_16">

	<?php if(!empty($this->rows['Nome'])){?>

	<div class="page-header">
		<h2>
			Matérial das Aulas de <?php echo $this->row->findParentRow('Application_Model_DbTable_Turma')->Nome; ?>
		</h2>
	</div>

<br />

	<table class="table table-striped data-table">
		<thead>
			<tr>
				<th><font size="3" color="black"><strong>#</strong></font></th>
				<th style="text-align: center;"><font size="3" color="black"><strong>Data da Publicação</strong></font></th>
				<th style="text-align: center;"><font size="3" color="black"><strong>Matérial</strong></font></th>
				<th style="text-align: center;"><font size="3" color="black"><strong>Ação</strong></font></th>
			</tr>
		</thead>
		<tbody>
		<?php foreach($this->rows as $lista){?>
			<tr style="background: #EEE;">
				<td style="width: 50px;"><strong><?php echo $lista->idArquivos; ?></strong></td>
				<td style="width: 300px; text-align: center;"><strong><?php echo $lista->Data; ?></strong></td>
				<td style="width: 300px; text-align: center;"><strong><?php echo $lista->Nome; ?></strong></td>
				<td style="text-align: center;">
					<a style="width: 50px; font-size: 12px;" class="btn btn-success" href="<?php echo $this->url(
						array(
							'controller'	=>	'minhasturmas',
							'action'		=>	'download',
							'idArquivo'		=>	$lista->idArquivos
						));?>">
							Download	
					</a>
				</td>
			</tr>		
		</tbody>
		<?php } ?>	
	</table>
	
	<?php } else { ?>
		<div class="page-header">
			<div style="color: #000; font-size: 30px;">
				<strong>Matérial de Aulas.</strong>
			</div>
		</div>
		
		<br /><br />
		
		<div style="color: red; font-size: 20px;">
			<strong>Nenhum matérial disponível até o momento.</strong>
		</div>
		
		<br /><br /><br /><br />
	<?php } 	?>

	<br /><br />
	
</div>