<?php $this->headTitle('Matérial de Aulas');?>

<div class="grid_16">

	<?php if(!empty($this->rows['Nome'])){?>

	<div class="page-header">
		<h2>
			Lista de turmas que há matérial de aulas disponíveis
		</h2>
	</div>
	
	<br />
	
	<table class="table table-striped data-table">
		<thead>
			<tr>
				<th><font size="3" color="black"><strong>#</strong></font></th>
				<th><font size="3" color="black"><strong>Turma</strong></font></th>
				<th style="text-align: center;"><font size="3" color="black"><strong>Ano / Semestre</strong></font></th>
				<th style="text-align: center;"><font size="3" color="black"><strong>Ação</strong></font></th>
			</tr>
		</thead>
		<tbody>
	
		<?php foreach($this->rows as $lista){?>
			<?php foreach($this->file as $file){?>
				<?php if($file->Turma_idTurma == $lista->findParentRow('Application_Model_DbTable_Turma')->idTurma){?>
					<tr style="background: #EEE;">
						<td style="width: 50px;"><strong><?php echo $file->Turma_idTurma;?></strong></td>
						<td style="width: 400px;"><strong><?php echo $lista->findParentRow('Application_Model_DbTable_Turma')->Nome;?></strong></td>
						<td style="width: 200px; text-align: center;"><strong><?php echo $lista->findParentRow('Application_Model_DbTable_Turma')->Ano . '/' . $lista->findParentRow('Application_Model_DbTable_Turma')->Semestre;?></strong></td>
						<td style="text-align: center;">
							<a style="width: 60px; font-size: 12px;" class="btn btn-primary" href="<?php echo $this->url(
								array(
									'controller'	=>	'minhasturmas',
									'action'		=>	'material',
									'idTurma'		=>	$lista->findParentRow('Application_Model_DbTable_Turma')->idTurma
									));?>">
								Exibir
							</a>
						</td>
					</tr>
				<?php }
			  }
		 }?>
		</tbody>
	</table>
	
	<?php } else { ?>
		<div class="page-header">
			<div style="color: #000; font-size: 30px;">
				<strong>Matérial Disponível.</strong>
			</div>
		</div>
		
		<br /><br />
		
		<div style="color: red; font-size: 20px;">
			<strong>Não há matérial disponível até o momento.</strong>
		</div>
		
		<br /><br /><br /><br />
	<?php } 	?>
	
	
	<br /><br />
	
</div>