<?php $this->headTitle('Chamada'); ?>

<div class="grid_16">

	<div class="page-header">	
		<?php if($this->row != null){
			foreach ($this->linha as $disc){?>
				<h2>Lista de chamada da Turma de <?php echo $disc->Nome;?></h2>
		<?php }?>	 
	</div>
		
	<br />
		
	<div class="container">	
		<form action="/professor/presenca/post-presenca" method="post" id="form-prof">
		<?php foreach($this->rows as $nome){
			if($nome->Status != 'inativo'){ ?>
			
				<h5><?php echo $nome->findParentRow('Application_Model_DbTable_Usuario')->Nome; ?></h5>
			
				
					<fieldset>
						<strong>Data</strong> 
							<input type="text" class="input-small" name="data[]" value="<?php print date('d/m/Y'); ?>"/>
						
					&nbsp;&nbsp;&nbsp;<strong>Faltas</strong>
							<input type="text" class="input-small" name="faltas[]"/>
						
							<input type="hidden" name="idMatricula[]" value="<?php echo $nome->idUsuario_has_Turma; ?>"/>
							<input type="hidden" name="idTurma[]" value="<?php echo $nome->Turma_idTurma; ?>"/>
							
						
					</fieldset>

			<?php }?>
		<?php } ?>
		<input class="btn btn-primary "type="submit" name="submit" value="Inserir"/>

		</form>
	</div>
	
	<br />
	
	<?php } else{
	
		echo '<h4>' . "Ainda não há alunos matriculados nessa disciplina" . '</h4>';
		
	 }?>

	 <br /><br />
</div>