<?php $this->headTitle('Lista')?>

<div class="grid_16">
	<div class="page-header">
		<h2>
			<?php foreach ($this->linha as $disc){?>
				Lista de alunos com faltas na turma de <?php echo $disc->Nome; ?>
			<?php }?>
		</h2>
	</div>
	
	<table class="table table-striped data-table" style="margin-bottom:0;">
		<thead>
			<tr>
				<th><h5>#</h5></th>
				<th><h5>Nome</h5></th>
				<th><h5>Data</h5></th>
				<th><h5>Faltas</h5></th>
				<th><h5>Ação</h5></th>
			</tr>
		</thead>
		<tbody>
			<?php $model = new Application_Model_DbTable_Matricula();?>
			<?php foreach($this->result as $lista){?>
				<tr>
					<td><strong><?php echo $lista->idPresenca; ?></strong></td>
					<?php $idUser = $lista->idUsuario_has_Turma;
							$query = $model->getId($idUser); ?>
					<td><strong><?php echo $query->findParentRow('Application_Model_DbTable_Usuario')->Nome; ?></strong></td>
					<td><strong><?php echo $lista->Data; ?></strong></td>
					<td><strong><?php echo $lista->Faltas; ?></strong></td>
					<td>
						<a class="btn btn-warning" href="<?php echo $this->url(
							array(
								'controller'	=>	'presenca',
								'action'		=>	'delete',
								'idPresenca'	=>	$lista->idPresenca
							));?>">
								Excluir
						</a>
					</td>
				</tr>
			<?php }?>
		</tbody>
	</table>
</div>