<?php $this->headTitle('Lista')?>

<div class="grid_16">

	<?php if(empty ($this->find['Turma_idTurma'])){ ?>
		<br /><br />
		<div style="color: red; font-size: 20px;">
			<strong>Ainda não há alunos matriculados nessa Turma.</strong>
		</div>
		
		<br /><br /><br /><br />
	<?php } else { 	?>

	<div class="page-header">
		<h2>
			<?php foreach ($this->linha as $disc){?>
				Lista de alunos com faltas na turma de <?php echo $disc->Nome; ?>
			<?php }?>
		</h2>
	</div>
	
	<table class="table table-striped data-table">
		<thead>
			<tr>
				<th style="padding-left: 30px;"><font size="3" color="black"><strong>#</strong></font></th>
				<th style="text-align: left;"><font size="3" color="black"><strong>Nome</strong></font></th>
				<th style="text-align: center;"><font size="3" color="black"><strong>Data</strong></font></th>
				<th style="text-align: center;"><font size="3" color="black"><strong>Faltas</strong></font></th>
				<th style="text-align: center;"><font size="3" color="black"><strong>Ação</strong></font></th>
			</tr>
		</thead>
		<tbody>
			<?php $model = new Application_Model_DbTable_Matricula();?>
			<?php foreach($this->result as $lista){?>
				<tr style="background: #EEE;">
					<td style="width: 50px; padding-left: 30px;"><strong><?php echo $lista->idPresenca; ?></strong></td>
					<?php $idUser = $lista->idUsuario_has_Turma;
							$query = $model->getId($idUser); ?>
					<td style="width: 300px;"><strong><?php echo $query->findParentRow('Application_Model_DbTable_Usuario')->Nome; ?></strong></td>
					<td style="width: 150px; text-align: center;"><strong><?php echo $lista->Data; ?></strong></td>
					<td style="width: 150px; text-align: center;"><strong><?php echo $lista->Faltas; ?></strong></td>
					<td style="text-align: center;">
						<a id="btn-turma" class="btn btn-danger" href="<?php echo $this->url(
							array(
								'controller'	=>	'presenca',
								'action'		=>	'delete',
								'idPresenca'	=>	$lista->idPresenca
							));?>">
								Excluir
						</a>
					</td>
				</tr>
			<?php }?>
		</tbody>
	</table>
	
	<br /><br /><br />
	
	<?php } ?>
	
</div>