<?php $this->headTitle('Inserir Serviços')?>

<div class="grid_16">

	<div class="page-header">
		<h2>Adicione serviços ao usuário <?php echo $this->row['Nome'];?></h2>
	</div>
	
	
	<?php echo $this->form; ?>
	
	<br /><br /><br />
	
	<div class="page-header">
		<h2>Lista de todos os serviços utilizados pelo usuário</h2>
	</div>
	
	<table class="table table-striped data-table">
		<thead>
			<tr>
				<th><h5>#</h5></th>
				<th><h5>Nome do Serviço</h5></th>
				<th><h5>Valor do Serviço</h5></th>
				<th><h5>Ação</h5></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->rows as $lista){?>
				<tr>
					<td><strong><?= $lista->findParentRow('Application_Model_DbTable_Servicos')->idServicos; ?></strong></td>
					<td><strong><?= $lista->findParentRow('Application_Model_DbTable_Servicos')->nome; ?></strong></td> 
					<td><strong><?= ' R$ ' . ' ' . $lista->findParentRow('Application_Model_DbTable_Servicos')->valor; ?></strong></td>
					<td>
						<a class="btn btn-warning" href="<?= $this->url(
							array(
								'controller'	=>	'usuarioservicos',
								'action'		=>	'delete',
								'idServico'		=>	$lista->Servicos_idServicos
							));?>">
								Excluir
						</a>
				</tr>
			<?php }?>
		</tbody>
	</table>

	<br />
</div>