<?php $this->headTitle('Inserir Serviços')?>

<div class="grid_16">

	<div class="page-header">
		<h2>Adicione serviços ao usuário <?php echo $this->row['Nome'];?></h2>
	</div>


	<?php echo $this->form; ?>

	<br /><br /><br />

	<div class="page-header">
		<h2>Lista de todos os serviços utilizados pelo usuário</h2>
	</div>
	
	
	<table class="table table-striped data-table">
		
		<thead>
		
		<tr>
			<th><h5>#</h5></th>
			<th><h5>Nome do Serviço</h5></th>
			<th style=" text-align: center;"><h5>Valor do Serviço</h5></th>
			<th style=" text-align: center;"><h5>Mês/Ano</h5></th>
			<th style=" text-align: center;"><h5>Ação</h5></th>
		</tr>
		</thead>
		<tbody>
		<?php foreach ($this->rows as $lista){
			$valor = ($lista->valor == NULL) ? $lista->findParentRow('Application_Model_DbTable_Servicos')->valor : $lista->valor;
		?>
			<tr>
				<td><strong><?php echo $lista->idUsuario_has_Servicos; ?></strong></td>
				<td><strong><?php echo $lista->findParentRow('Application_Model_DbTable_Servicos')->nome; ?></strong></td>
				<td style="width: 300px; text-align: center;"><strong>
						<?php echo ' R$ ' . ' ' . number_format($valor,2,',','.'); ?>
					</strong>
				</td>
				<td style="width: 300px; text-align: center;"><strong><?php echo $lista->mes . '/' . $lista->ano; ?></strong></td>
				<td style=" width: 100px; text-align: center;">
					<a class="btn btn-warning" href="<?php echo $this->url(
						array(
							'controller'				=>	'usuarioservicos',
							'action'					=>	'delete',
							'idUsuario_has_Servicos'		=>	$lista->idUsuario_has_Servicos
						));?>">
						Excluir
					</a>
				</td>
				<?php echo $this->msg; ?>
			</tr>
		<?php }?>
		</tbody>
	</table>
	
	</div>
	
	<br /><br />
