<?php $this->headTitle('Histórico');?>

<div class="grid_16" >
	<div class="page-header">
		<h2>Histórico Escolar</h2>
	</div>
	
	<br />
<?php

if (! empty ($this->row['Turma_idTurma'])){

	$tableNota = new Application_Model_DbTable_Nota();
	$presenca = new Application_Model_DbTable_Presenca();

	$file = APPLICATION_PATH . '/models/Historico/Historico-aluno.pdf';
 
	$pdf = Zend_Pdf::load($file);
	$page = $pdf->pages[0];
	$font = Zend_Pdf_Font::fontWithName(Zend_Pdf_Font::FONT_TIMES_ROMAN);
	$page->setFont($font, 9);
 
	$posY = 600;
 
	foreach ($this->rows as $users){
	
		$id = $users->idUsuario_has_Turma;
		$chamada = $presenca->contaPresenca($id);
		$media = $tableNota->nota($id);
	
		
			$page->drawText($users->findParentRow('Application_Model_DbTable_Usuario')->Nome, 125, 651.5);
			$page->drawText($users->findParentRow('Application_Model_DbTable_Turma')->Nome, 57, $posY); 
			$page->drawText($users->findParentRow('Application_Model_DbTable_Turma')->Ano . '.', 250, $posY); 
			$page->drawText($users->findParentRow('Application_Model_DbTable_Turma')->Semestre, 272, $posY);
		
		
			$page->drawText(substr($media['unit1']/3,0,4), 400, $posY);
		
			$page->drawText($users->Status, 497, $posY);
		
		$posY -=22.7;
	
	}

	header("Content-Type: application/x-pdf");
	header("Content-Disposition: attachment; filename=Histórico" . ".pdf");
	
	echo $pdf->render();

}	
else{
	echo '<h4>' . 'Usuário Matricula em nenhuma Turma até o momento' . '</h4>';
}
?>

	<br /><br />

</div>