<?php $this->headTitle('Matérial de Aulas'); ?>

<div class="grid_16">
	<div class="page-header">
		<h2>
			Matérial das Aulas de <?php echo $this->row->findParentRow('Application_Model_DbTable_Disciplina')->Disciplina; ?>
		</h2>
	</div>

<br />

<?php if(!empty($this->rows['Nome'])){?>

	<table class="table table-striped data-table" style="margin-bottom:0;">
		<thead>
			<tr>
				<th><h5>#</h5></th>
				<th><h5>Data da Publicação</h5></th>
				<th><h5>Matérial</h5></th>
				<th><h5>Ação</h5></th>
			</tr>
		</thead>
		<tbody>
		<?php foreach($this->rows as $lista){?>
			<tr>
				<td><strong><?php echo $lista->idArquivos; ?></strong></td>
				<td><strong><?php echo $lista->Data; ?></strong></td>
				<td><strong><?php echo $lista->Nome; ?></strong></td>
				<td>
					<a class="btn btn-success" href="<?php echo $this->url(
						array(
							'controller'	=>	'minhasturmas',
							'action'		=>	'download',
							'idArquivo'		=>	$lista->idArquivos
						));?>">
							Download	
					</a>
				</td>
			</tr>		
	<?php }
}else{
		echo '<h4>' . 'Nenhum matérial disponível no momento!' . '</h4>';
	}
	?>
	</tbody>
</table>

	<br /><br />
	
</div>