<?php $this->headTitle('Matérial de Aulas');?>

<div class="grid_16">
	<div class="page-header">
		<h2>
			Lista de Turmas em que há matérial de aulas disponíveis
		</h2>
	</div>
	
	<br />
	
	<?php if(!empty($this->rows['Nome'])){?>
	
	<table class="table table-striped data-table" style="margin-bottom:0;">
		<thead>
			<tr>
				<th style="padding-left: 30px;"><font size="3" color="black"><strong>#</strong></font></th>
				<th style="text-align: center; "><font size="3" color="black"><strong>Turma</strong></font></th>
				<th style="text-align: center; "><font size="3" color="black"><strong>Ano / Semestre</strong></font></th>
				<th style="text-align: center; "><font size="3" color="black"><strong>Ação</strong></font></th>
			</tr>
		</thead>
		<tbody>
			
			<?php foreach($this->rows as $lista){?>
				<?php foreach($this->file as $file){?>
					<?php if($file->Disciplina_idDisciplina == $lista->findParentRow('Application_Model_DbTable_Turma')->Disciplina_idDisciplina){?>
						<tr style="background: #EEE; ">
							<td style="width: 50px; padding-left: 30px;"><strong><?php echo $lista->findParentRow('Application_Model_DbTable_Turma')->Disciplina_idDisciplina;?></strong></td>
							<td style="width: 350px; text-align: center;"><strong><?php echo $lista->findParentRow('Application_Model_DbTable_Turma')->Nome;?></strong></td>
							<td style="width: 150px; text-align: center; "><strong><?php echo $lista->findParentRow('Application_Model_DbTable_Turma')->Ano . '/' . $lista->findParentRow('Application_Model_DbTable_Turma')->Semestre;?></strong></td>
							<td style="text-align: center;">
								<a id="btn-turma" class="btn btn-primary" href="<?php echo $this->url(
									array(
										'controller'	=>	'minhasturmas',
										'action'		=>	'material',
										'idDisciplina'	=>	$lista->findParentRow('Application_Model_DbTable_Turma')->Disciplina_idDisciplina
										));?>">
									Exibir
								</a>
							</td>
						</tr>
					<?php }
				 	}
				}?>
			</tbody>
		</table>
	
	<?php
	}
	else{
		
		echo '<h4>' . 'Não há matérial disponível até o momento.' . '</h4>';
		
	 }?>	
		
	<br /><br />	
</div>