<?php $this->headTitle('Matérial de Aulas');?>

<div class="grid_16">
	<div class="page-header">
		<h2>
			Lista de Turmas em que há matérial de aulas disponíveis
		</h2>
	</div>
	
	<br />
	
	<table class="table table-striped data-table" style="margin-bottom:0;">
	<?php if(!empty($this->rows['Nome'])){?>
		<thead>
			<tr>
				<th>#</th>
				<th>Turma</th>
				<th>Ação</th>
			</tr>
		</thead>
		<tbody>
	<?foreach($this->rows as $lista){?>
			<tr>
				<td><?php echo $lista->findParentRow('Application_Model_DbTable_Turma')->Disciplina_idDisciplina;?></td>
				<td><?php echo $lista->findParentRow('Application_Model_DbTable_Turma')->Nome;?></td>
				<td>
					<a class="btn btn-default" href="<?php echo $this->url(
						array(
							'controller'	=>	'minhasturmas',
							'action'		=>	'material',
							'idDisciplina'	=>	$lista->findParentRow('Application_Model_DbTable_Turma')->Disciplina_idDisciplina
						));?>">
							Exibir
					</a>
				</td>
			</tr>

	<?php }
	
	}else{?>
		
			<strong><?= 'Não há matérial disponível até o momento.'; ?></strong>
		
	<?php }?>	
		</tbody>
	</table>
</div>