<?php

if(! empty($this->row['Turma_idTurma'])){


	header("Content-type: text/html; charset=utf-8");
	ob_start();
	?>
	
	<table>
		<tr>
			<th><img src="/images/logosibb2.gif" height="120px" width="120px"></th>
			<th width="550px">
				<font size="5">SEMINÁRIO E INSTITUTO BATISTA BEREIANO</font>
				<p><font size="3">Rua Mar do Leste, 100, Pajuçara - CEP: 59.133-380 / Natal-RN</font></p>
				<p><font size="3" color="#000;">Email: <span style="color:blue">sibbereiano@gmail.com</span></font></p>
				<p><font size="3" color="#000;">Fone: (084) 3221-2520 / 3201-0083 </font></p>
			</th>
		</tr>
	</table>
	<hr />
	
	<br />
	
	<h3 style="text-align: center">Histórico Escolar</h3>
	
	<br />
	
	Aluno(a):<strong><?php echo $this->row->findParentRow('Application_Model_DbTable_Usuario')->Nome;?></strong>
	Curso: <strong><?php echo $this->row->findParentRow('Application_Model_DbTable_Usuario')->findParentRow('Application_Model_DbTable_Curso')->Nome; ?></strong></p>
	
	<br /><br />
	
	<table border="1" cellpadding="5px" cellspacing="0" style="border-collapse: collapse;">
		<thead>
			<tr>
				<th width="150px">Disciplina</th>
				<th width="50px">Créditos</th>
				<th width="10px">Ano/Semestre</th>
				<th width="50px">Faltas</th>
				<th width="70px">Média</th>
				<th width="100px">Situação</th>
			</tr>
		</thead>
	
	
	<?php 
	
	$tableNota = new Application_Model_DbTable_Nota();
	$presenca = new Application_Model_DbTable_Presenca();
	
	$i = 0;
	$c = 0;
	
	foreach($this->rows as $users){?>
	
	<?php 
	$id = $users->idUsuario_has_Turma;
	$chamada = $presenca->contaPresenca($id);
	$media = $tableNota->media($id);
	$cred = $users->findParentRow('Application_Model_DbTable_Turma')->findParentRow('Application_Model_DbTable_Disciplina')->QntdCred;
	?>
	
		<tr <?php //if($i % 2 == 0) : ?>> <!-- style="background: #EEE " --><?php //endif;?>
			<td style="text-align: center;"><?php echo $users->findParentRow('Application_Model_DbTable_Turma')->findParentRow('Application_Model_DbTable_Disciplina')->Disciplina; ?></td>

			<td style="text-align: center;" ><?php echo $users->findParentRow('Application_Model_DbTable_Turma')->findParentRow('Application_Model_DbTable_Disciplina')->QntdCred; ?></td>

			<td style="text-align: center;"><?php echo $users->findParentRow('Application_Model_DbTable_Turma')->Ano . '/' . $users->findParentRow('Application_Model_DbTable_Turma')->Semestre; ?></td>
			
			<?php if($chamada["SUM(Faltas)"] != 0){?>
					<td style="text-align: center; "><?php echo $chamada["SUM(Faltas)"]; ?></td>			
			<?php }
				else{?>
		 
					<td style="text-align: center; "><?php echo " - "; ?></td>

			<?php }?>
			
			<?php if($media < 7){ ?>
				<td style="text-align: center; color:red; "><?php echo number_format($media, 1,',','.'); ?></td>
			<?php } else { ?>
				<td style="text-align: center; "><?php echo number_format($media, 1,',','.'); ?></td>
			<?php } ?>
			<td style="text-align: center; "><?php echo $users->Status; ?></td>

		<?php $c = $c + $cred; ?>
			
	<?php }?>
	
	</table>	

	<br /><hr />
	
	Total de Créditos: <strong><?php echo $c; ?></strong> </p>
	
	
	<?php 
	$html = ob_get_contents();
	ob_end_clean();
	
	define('MPDF_PATH', APPLICATION_PATH . '/../library/mpdf/');
	
	include(MPDF_PATH .'mpdf.php');
	
	$mpdf = new mPDF('pt','A4',11);
	
	$mpdf->allow_charset_conversion = true;
	$mpdf->charset_in = 'utf-8';
	
	$mpdf->SetDisplayMode('fullpage');
	//$mpdf->SetHeader('Seminário e Instituto Batista Bereiano - Histórico Escolar');
	$mpdf->SetFooter('Histórico gerado no dia {DATE j/m/Y} | {PAGENO}');
	$mpdf->WriteHTML($html);
	
	$arquivo = Histórico . ' - ' . $this->row->findParentRow('Application_Model_DbTable_Usuario')->Nome . '.pdf';
	
	$mpdf->Output($arquivo, 'D');
	
	exit();
	
	?>
	
	<?php }
		else{
			echo '<h4>' . 'Usuário Matricula em nenhuma Turma até o momento' . '</h4>';
	} ?>

	<br /><br />
	
