<?php 

 $tableNota = new Application_Model_DbTable_Nota();
 $presenca = new Application_Model_DbTable_Presenca();

$file = APPLICATION_PATH . '/models/Historico/Historico.pdf';
 
 $pdf = Zend_Pdf::load($file);
 $page = $pdf->pages[0];
 $font = Zend_Pdf_Font::fontWithName(Zend_Pdf_Font::FONT_TIMES_ROMAN);
 $page->setFont($font, 10);
 
 $posY = 600;
 
foreach ($this->rows as $users){

	$id = $users->idUsuario_has_Turma;
	$chamada = $presenca->contaPresenca($id);
	$media = $tableNota->nota($id);
	
		
		
		$page->drawText($users->findParentRow('Application_Model_DbTable_Usuario')->Nome, 125, 651.5);
		$page->drawText($users->findParentRow('Application_Model_DbTable_Turma')->Nome, 57, $posY); 
		$page->drawText($users->findParentRow('Application_Model_DbTable_Turma')->Ano . '.', 208, $posY); 
		$page->drawText($users->findParentRow('Application_Model_DbTable_Turma')->Semestre, 230, $posY);
		
		if($chamada["SUM(Faltas)"] != null){
			
			$page->drawText($chamada["SUM(Faltas)"], 320, $posY);
			
		} else{
		 
			$page->drawText(0, 324, $posY);

		}
		
		$page->drawText(substr($media['unit1']/3,0,4), 405, $posY);
		
		$page->drawText($users->Status, 497, $posY);
		
	$posY -=22.7;
}


	header("Content-Type: application/x-pdf");
	header("Content-Disposition: attachment; filename=Histórico" . ".pdf");
	
	echo $pdf->render();


?>
