<?php $this->headTitle('Matrícula'); ?>

<div class="grid_16">
  	<div class="page-header">
	    <h1>Alunos Matriculados
		    <small>Veja toda a lista de alunos Matriculados</small>
	    </h1>
  	</div>
  	<table class="table table-striped data-table" style="margin-bottom:0;">
	    <thead>
	      <tr>
	        <th><h5>#</h5></th>
	        <th><h5>Nome</h5></th>
	        <th><h5>Turma</h5></th>
	        <th><h5>Professor</h5></th>
	        <th><h5>Ações</h5></th>
	      </tr>
	    </thead>
	    <tbody>
<?php foreach ($this->rows as $lista) { ?>
	<tr>
		<td><strong><?= $lista->idUsuario_has_Turma; ?></strong></td>
		<td><strong><?= $lista->findParentRow('Application_Model_DbTable_Usuario')->Nome; ?></strong></td>
		<td><strong><?= $lista->findParentRow('Application_Model_DbTable_Turma')->Nome . ' ' .
							$lista->findParentRow('Application_Model_DbTable_Turma')->Ano . '.' . 
							$lista->findParentRow('Application_Model_DbTable_Turma')->Semestre; ?></strong></td>
		<td><strong>					
		<?php foreach ($this->prof as $prof){?>
				<?php if($prof->findParentRow('Application_Model_DbTable_Usuario')->idUsuario == 
						 $lista->findParentRow('Application_Model_DbTable_Turma')->idUsuario){?>
						Professor(a): <?= $prof->findParentRow('Application_Model_DbTable_Usuario')->Nome;?>
										 
				<?php }?> <!-- fim if -->
			
		<?php }?> <!-- fim foreach -->
		</strong></td>
		<td>
			<a class="btn btn-warning" href="<?= $this->url(
				array(
					'controller'			=>	'matricula',
					'action'				=>	'delete',
					'idUsuario_has_Turma'	=>	$lista->idUsuario_has_Turma
				));
			?>">Excluir</a>
		</td>
	</tr>
	
<?php }?> <!-- fim foreach -->
</table>

	<br />
</div>
