<?php $this->headTitle('Matrícula'); ?>

<div class="grid_16">
  	<div class="page-header">
	    <h1>Alunos Matriculados
		    <small>Veja toda a lista de alunos Matriculados</small>
	    </h1>
  	</div>
  	<table class="table table-striped data-table">
	    <thead>
	      <tr>
	        <th><font size="3" color="black"><strong>#</strong></font></th>
	        <th><font size="3" color="black"><strong>Nome</strong></font></th>
	        <th style="padding-left: 50px"><font size="3" color="black"><strong>Turma</strong></font></th>
	        <th><font size="3" color="black"><strong>Professor</strong></font></th>
	        <th style="padding-left: 20px"><font size="3" color="black"><strong>Ações</strong></font></th>
	      </tr>
	    </thead>
	    <tbody>
<?php foreach ($this->rows as $lista) { ?>
	<tr style="background: #EEE;">
		<td style="width: 50px;"><strong><?php echo $lista->idUsuario_has_Turma; ?></strong></td>
		<td style="width: 250px;"><strong><?php echo $lista->findParentRow('Application_Model_DbTable_Usuario')->Nome; ?></strong></td>
		<td style="width: 300px;"><strong><?php echo $lista->findParentRow('Application_Model_DbTable_Turma')->Nome . ' ' .
							$lista->findParentRow('Application_Model_DbTable_Turma')->Ano . '.' . 
							$lista->findParentRow('Application_Model_DbTable_Turma')->Semestre; ?></strong></td>
		<td style="width: 250px;"><strong>					
		<?php foreach ($this->prof as $prof){?>
				<?php if($prof->findParentRow('Application_Model_DbTable_Usuario')->idUsuario == 
						 $lista->findParentRow('Application_Model_DbTable_Turma')->idUsuario){?>
						<?php echo $prof->findParentRow('Application_Model_DbTable_Usuario')->Nome;?>
										 
				<?php }?> <!-- fim if -->
			
		<?php }?> <!-- fim foreach -->
		</strong></td>
		<td>
			<a style="width: 50px; font-size: 12px;" class="btn btn-danger" href="<?php echo $this->url(
				array(
					'controller'			=>	'matricula',
					'action'				=>	'delete',
					'idUsuario_has_Turma'	=>	$lista->idUsuario_has_Turma
				));
			?>">Excluir</a>
		</td>
	</tr>
	
<?php }?> <!-- fim foreach -->
</table>

	<br /><br />
</div>