<?php $this->headTitle('Matricular');?>



<div class="grid_16">
  	<div class="page-header">
	    <h1>Matricular Aluno
		    <small>Gerenciamento de matrículas</small>
	    </h1>
  	</div>
  	
<br />  	
  	
  	<div class="container">
  		<div class="form">
  			<?php echo $this->form ?>
  				<span class="errors"><?php echo $this->messages; ?></span>
  		</div>
  	</div>  	  	
  	
  	<br /><br /><br /><br />
  	
</div>