<?php $this->headTitle('Listar Igrejas'); ?>

<div class="grid_16">
  	<div class="page-header">
	    <h1>Igrejas Cadastradas
	    	<small>Veja toda a lista das igrejas cadastradas</small>
	    </h1>
  	</div>
  	<table class="table table-striped data-table" style="margin-bottom:0;">
	    <thead>
	      <tr>
	        <th><h5>#</h5></th>
	        <th><h5>Igreja</h5></th>
	        <th><h5>Pastor</h5></th>
	        <th><h5>Telefone</h5></th>
	        <th><h5>Ações</h5></th>
	      </tr>
	    </thead>
	    <tbody>
	<?php foreach($this->rows as $lista){?>
		<tr>
			<td><strong><?php echo $lista->idIgreja; ?></strong></td>
			<td><strong><?php echo $lista->Igreja; ?></strong></td>
			<td>
				<strong>
					<?php if($lista->Telefone == null){
						echo ' - ';
					} else{
						echo $lista->Telefone;
					}
					?>
				</strong>
			</td>
			<td><strong><?php echo $lista->Pastor?></strong></td>
			<td>
				<a class="btn btn-info" href="<?php echo $this->url(
					array(
						'controller'	=>	'igreja',
						'action'		=>	'detalhes',
						'idIgreja'		=>	$lista->idIgreja
					))?>">
					<i class="icon-search icon-grey"></i>
				</a>
			
				<a class="btn btn-primary" href="<?php echo $this->url(
					array(
						'controller'	=>	'igreja',
						'action'		=>	'editar',
						'idIgreja'		=>	$lista->idIgreja
					))?>">
						Editar
				</a>
				
				<a class="btn btn-warning" href="<?php echo $this->url(
					array(
						'controller'	=>	'igreja',
						'action'		=>	'delete',
						'idIgreja'		=>	$lista->idIgreja
					))?>">
						Excluir	
				</a>
			</td>
		</tr>
	<?php } ?>
	</tbody>
</table>

	<br /><br />
</div>