<?php echo $this->partial("_header.phtml","admin"); ?>

<link rel="shortcut icon favicon" href="../../images/logosibb.ico">
	<div id="pjax">
		<div id="wrapper" data-adminica-nav-top="1" data-adminica-side-top="1" class="has_fixed_bar">
			<?php echo $this->partial('components/topbar.php');?>
			<?php echo $this->partial('components/sidebar.php'); ?>
			<?php echo $this->partial('components/stackbar.php');?>			
		</div>
			<?php echo $this->partial('components/navbar-fixed.php');?>
			
			<div id="main_container" class="main_container container_16 clearfix">
			<?php if( isset($this->messages) ) : ?>
				<div class="alert">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
					<strong>Atenção!</strong> <br />
					<?= implode('<br />', $this->messages); ?>
				</div>
				<?php endif; ?>
			
				<?= $this->layout()->content; ?>
				
			</div>
	</div>
	<?php echo $this->partial('dialogs/dialog_welcome.php', 'admin');?>
	<?php echo $this->partial('dialogs/dialog_logout.php', 'admin');?>
<?php echo $this->partial('_footer.phtml', 'admin');?>