<div class="grid_16">
  	<div class="page-header">
	    <h1>Usuários Cadastrado
		    <small>Veja toda a lista de usuários cadastrados</small>
	    </h1>
  	</div>

	<table class="table table-striped data-table">
		<thead>
			<tr>
				<th><font size="3" color="black"><strong>Usuário</strong></font></th>
				<th style="text-align: center;"><font size="3" color="black"><strong>Tipo</strong></font></th>
				<th style="text-align: center;"><font size="3" color="black"><strong>Telefone</strong></font></th>
				<th style="text-align: center;"><font size="3" color="black"><strong>Igreja</strong></font></th>
				<th style="text-align: center;"><font size="3" color="black"><strong>Ações</strong></font></th>
			</tr>
		</thead>
		<tbody>
	<?php foreach ($this->rows as $lista){?>
		<tr style="background: #EEE;">
			<td style="width: 210px;"><strong><?php echo $lista->Nome; ?></strong></td>
			<td style="width: 70px; text-align: center;"><strong>
				<?php switch ($lista->Tipo) {
					case 1:
						echo "Admin";
						break;
					case 2:
						echo "Professor";
						break;
					case 3:
						echo "Aluno";
						break;
				} ?>
			</strong></td>
			<td style="width: 100px; text-align:center;"><strong><?php echo $lista->Telefone; ?></strong></td>
			<td style="width: 260px;"><strong><?php echo $lista->findParentRow('Application_Model_DbTable_Igreja')->Igreja; ?></strong></td>
			<td>
				<a class="btn btn-info" href="<?php echo $this->url(
					array(
						'controller'	=>	'usuario',
						'action'		=>	'detalhes',
						'idUsuario'		=>	$lista->idUsuario	
					))?>">
					<i class="icon-search icon-grey"></i>
				</a>
				
			
				<a id="btn-admin" class="btn btn-primary" href="<?php echo $this->url(
					array(
						'controller'	=>	'usuario',
						'action'		=>	'editar',
						'idUsuario'		=>	$lista->idUsuario
					));?>">
					Editar
				</a>
			
				<a id="btn-admin" class="btn btn-success" href="<?php echo $this->url(
					array(
						'controller'	=>	'historico',
						'action'		=>	'usuario',
						'idUsuario'		=>	$lista->idUsuario
					));?>">

						Histórico
				</a>
				
				<a id="btn-admin" class="btn btn-warning" href="<?php echo $this->url(
					array(
						'controller'	=>	'usuarioservicos',
						'action'		=>	'index',
						'idUsuario'		=>	$lista->idUsuario
					));?>">
						Serviços

				</a>
	
				<a id="btn-admin" class="btn btn-danger" href="<?php echo $this->url(
					array(
						'controller'	=>	'usuario',
						'action'		=>	'delete',
						'idUsuario'		=>	$lista->idUsuario
					));?>">
					Excluir
				</a></td>
		</tr>
	
<?php }  ?>
	</tbody>
	</table>

	<br /><br />
</div>