<div class="grid_16">
  	<div class="page-header">
	    <h1>Usuários Cadastrado
		    <small>Veja toda a lista de usuários cadastrados<small>
	    </h1>
  	</div>

	<table class="table table-striped data-table">
		<thead>
			<tr>
				<th>Nome</th>
				<th>Tipo</th>
				<th>Telefone</th>
				<th>E-mail</th>
				<th>Igreja</th>
				<th>Ações</th>
			</tr>
		</thead>
		<tbody>
	<?php foreach ($this->rows as $lista){?>
		<tr>
			<td><?php echo $lista->Nome ?></td>
			<td>
				<?php switch ($lista->Tipo) {
					case 1:
						echo "Admin";
						break;
					case 2:
						echo "Professor";
						break;
					case 3:
						echo "Aluno";
						break;
				} ?>
			</td>
			<td><?php echo $lista->Email ?></td>
			<td><?php echo $lista->Telefone ?></td>
			<td><?php echo $lista->findParentRow('Application_Model_DbTable_Igreja')->Igreja; ?></td>
			<td><a class="btn btn-primary" href="<?php echo $this->url(
					array(
						'controller'	=>	'usuario',
						'action'		=>	'editar',
						'idUsuario'		=>	$lista->idUsuario
					));?>">
						<img title="Editar" src="/../images/ico_editar.gif" alt="Editar" width="20" height="20"></img>
				</a>
			
				<a class="btn"href="<?php echo $this->url(
					array(
						'controller'	=>	'historico',
						'action'		=>	'usuario',
						'idUsuario'		=>	$lista->idUsuario
					));?>">
						<img title="Histórico" src="/../images/historico.png" alt="Historico" width="20" height="20"></img>
				</a>
				
				<a class="btn" href="<?php echo $this->url(
					array(
						'controller'	=>	'usuarioservicos',
						'action'		=>	'index',
						'idUsuario'		=>	$lista->idUsuario
					));?>">
						<img title="Serviços" src="" alt=""></img>
				</a>
	
				<a class="btn btn-warning" href="<?php echo $this->url(
					array(
						'controller'	=>	'usuario',
						'action'		=>	'delete',
						'idUsuario'		=>	$lista->idUsuario
					));?>">
						<img title="Excluir" src="/../images/excluir.gif" alt="Excluir" width="20" height="20"></img>
				</a></td>
		</tr>
	
<?php }  ?>
	</tbody>
	</table>


		<?php if($this->query != false){
			foreach($this->query as $data){
				if($data->idUsuario == $lista->idUsuario){
					echo '<div id="user_res">' . $lista->Nome . '</div>';
					if($lista->Tipo == 1){
						echo '<div id="tipo_res">' . "Admin" . '</div>';	
					}
					if($lista->Tipo == 2){
						echo '<div id="tipo_res">' . "Professor" . '</div>';
					}
					if($lista->Tipo == 3){
						echo '<div id="tipo_res">' . "Aluno" . '</div>';
					}
					echo '<div id="email_res">' . $lista->Email . '</div>';
					echo '<div id="fone_res">' . $lista->Telefone . '</div>';
					echo '<div id="igreja_res">' . $lista->findParentRow('Application_Model_DbTable_Igreja')->Igreja . '</div>';
					echo '<div id="action_res">'; ?>
					<a href="<?php echo $this->url(
						array(
							'controller'	=>	'usuario',
							'action'		=>	'editar',
							'idUsuario'		=>	$lista->idUsuario
						));?>">
							<img title="Editar" src="/../images/ico_editar.gif" alt="Editar" width="20" height="20"></img>
					</a>
					
					<a href="<?php echo $this->url(
						array(
							'controller'	=>	'historico',
							'action'		=>	'usuario',
							'idUsuario'		=>	$lista->idUsuario
						));?>">
							<img title="Historico" src="/../images/historico.png" alt="Historico" width="20" height="20"></img>
					</a>
						
					<a href="<?php echo $this->url(
						array(
								'controller'	=>	'usuario',
								'action'		=>	'delete',
								'idUsuario'		=>	$lista->idUsuario
						));?>">
							<img title="Excluir" src="/../images/excluir.gif" alt="Excluir" width="20" height="20"></img>
					</a>
					
					<?php echo '</div>';?>
			<?php }
			}
		}
?>

</div>