<div class="grid_16">
  	<div class="page-header">
	    <h1>Usuários Cadastrado
		    <small>Veja toda a lista de usuários cadastrados</small>
	    </h1>
  	</div>

  	<div>
	<table class="table table-striped data-table">
		<thead>
			<tr>
				<th><font size="2" color="black"><strong>Usuário</strong></font></th>
				<th style="text-align: center;"><font size="2" color="black"><strong>Tipo</strong></font></th>
				<th style="text-align: center;"><font size="2" color="black"><strong>Igreja</strong></font></th>
				<th style="text-align: center;"><font size="2" color="black"><strong>Ações</strong></font></th>
			</tr>
		</thead>
		<tbody>
		
	<?php foreach ($this->rows as $lista){?>
		<tr style="background: #EEE;">
			<td><strong><?php echo $lista->Nome; ?></strong></td>
			<td style="width: 70px; text-align: center;"><strong>
				<?php switch ($lista->Tipo) {
					case 1:
						echo "Admin";
						$tipo = '01';
						break;
					case 2:
						echo "Professor";
						$tipo = '02';
						break;
					case 3:
						echo "Aluno";
						$tipo = '03';
						break;
				} ?>
			
			<?php switch ($lista->findParentRow('Application_Model_DbTable_Curso')->Nome) {
				case 'Bíblico Geral':
					$curso = '01';	
					break;
				case 'Bacharel em Teologia':
					$curso = '02';
					break;
				case 'Bacharel em Missões':
					$curso = '03';
					break;
				case 'Bacharel em Educação Cristã':
					$curso = '04';
					break;
				case 'Pastoral (Teológico)':
					$curso = '05';
					break;
				default:
					$curso = '06';
					break;
			} ?>
					
			
				
			
			</strong></td>
			<td style="width: 230px; text-align:center;"><strong><?php echo $lista->findParentRow('Application_Model_DbTable_Igreja')->Igreja; ?></strong></td>
			<td  style="text-align: center; width: 500px;"><a class="btn btn-info" data-toggle="modal" href="#myModal-<?php echo $lista->idUsuario; ?>"><i class="icon-search icon-grey"></i></a>
			
			<div id="myModal-<?php echo $lista->idUsuario; ?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-header">
    				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    					<h3 id="myModalLabel">Dados Cadastrais do Usuário</h3>
  				</div>
  				<div class="modal-body">
    				<div style="margin: 0 0px 0 30px; width: 100px;"><img src="/files/<?php echo $lista->Foto; ?>" width="100" height="120"></img></div>
    				<div style="margin: -120px 0px 0 140px; text-align: left;">
    						
    						<p><strong><font size="2">Matrícula: <span style="color:#069;"><?php echo $lista->Ano . $tipo . $curso . $lista->idUsuario; ?></span></font></strong></p>
    						<p><strong><font size="2">Nome do Usuário: <span style="color:#069;"><?php echo $lista->Nome; ?></span></font></strong></p>
    						<p><strong><font size="2">Endereço: <span style="color:#069;"><?php echo $lista->Endereco; ?></span></font></strong></p>
    						<p><strong><font size="2">CEP: <span style="color:#069;"><?php echo $lista->CEP; ?></span></font></strong></p>
    						<p><strong><font size="2">Telefone(s): <span style="color:#069;"><?php echo $lista->Telefone . ' / ' . $lista->Celular; ?></span></font></strong></p>
    						<p><strong><font size="2">Data de Nascimento: <span style="color:#069;"><?php echo $lista->DataNascimento; ?></span></font></strong></p>
    						<p><strong><font size="2">CPF: <span style="color:#069;"><?php echo $lista->CPF; ?></span></font></strong></p>
    						<p><strong><font size="2">Nome da Mãe: <span style="color:#069;"><?php echo $lista->NomeMae; ?></span></font></strong></p>
    						<p><strong><font size="2">Nome do Pai: <span style="color:#069;"><?php echo $lista->NomePai; ?></span></font></strong></p>
    						<p><strong><font size="2">E-mail: <span style="color:#069;"><?php echo $lista->Email; ?></span></font></strong></p>
    						<p><strong><font size="2">Igreja: <span style="color:#069;"><?php echo $lista->findParentRow('Application_Model_DbTable_Igreja')->Igreja; ?></span></font></strong></p>
    						<p><strong><font size="2">Curso: <span style="color:#069;"><?php echo $lista->findParentRow('Application_Model_DbTable_Curso')->Nome; ?></span></font></strong></p>
    						<p><strong><font size="2">Tipo: <span style="color:#069;"><?php switch ($lista->Tipo) {
									case 1:
										echo "Administrador";
										break;
									case 2:
										echo "Professor";
										break;
									case 3:
										echo "Aluno";
										break;
									} ?></span></font></strong></p>
    					
    				</div>
  				</div>
  				<div class="modal-footer">
    				<button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
				</div>
			</div>
			
			
				<a id="btn-padrao" class="btn btn-inverse" href="<?php echo $this->url(
					array(
						'controller'	=>	'historico',
						'action'		=>	'usuario',
						'idUsuario'		=>	$lista->idUsuario
					));?>">

						Histórico
				</a>
				
				<a id="btn-padrao" class="btn btn-default" href="<?php echo $this->url(
					array(
						'controller'	=>	'usuarioservicos',
						'action'		=>	'index',
						'idUsuario'		=>	$lista->idUsuario
					));?>">
						Serviços

				</a>

				<a id="btn-padrao" class="btn btn-warning" href="/admin/debitos?aluno=<?php echo $lista->idUsuario; ?>">
					Débitos
				</a>

				<a style="color:black;" id="btn-padrao" class="btn btn-info" href="/admin/faturas?aluno=<?php echo $lista->idUsuario; ?>">
					Faturas
				</a>

				<a id="btn-padrao" class="btn btn-primary" href="<?php echo $this->url(
					array(
						'controller'	=>	'usuario',
						'action'		=>	'editar',
						'idUsuario'		=>	$lista->idUsuario
					));?>">
					Editar
				</a>
				
				<?php if($lista->Status == 'ativo'){?>
				
				<a id="btn-padrao" class="btn btn-danger" href="<?php echo $this->url(
					array(
						'controller'	=>	'usuario',
						'action'		=>	'desativa',
						'idUsuario'		=>	$lista->idUsuario
					));?>">
					Desativar
				</a>
				
				<?php } else { ?>
				
				<a id="btn-padrao" class="btn btn-success" href="<?php echo $this->url(
					array(
						'controller'	=>	'usuario',
						'action'		=>	'ativa',
						'idUsuario'		=>	$lista->idUsuario
					));?>">
					Ativar
				</a>
				
				<?php } ?>
			
			</td>
		</tr>
	
<?php }  ?>
		
	</tbody>
	</table>
	

	<br /><br />
	
	</div>
</div>