<?php $this->headTitle('Cadastrar Usuário'); ?>

<div class="grid_16">
  	<div class="page-header">
	    <h1>Cadastrar novo usuário
		    <small>Preencha o formulário abaixo para cadastrar um usuário</small>
	    </h1>
  	</div>
  	
<br />  	
  
	<div class="container">
		<div class="grid_14">
			<div id="form">
				<?php echo $this->form; ?>
			</div>
		</div>
	</div>
		
	<br /><br /><br />
</div>